project:
  type: book

book:
  favicon: figure/favicon_book.png
  title: "Artifact Corrections for Effect Sizes"
  subtitle: "Implementation in R and Application to Meta-Analysis"
  twitter-card: 
    creator: "@MatthewBJane"
    image: figure/twitter-card-image.png
  page-navigation: true
  url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  site-url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  date: "10/08/2023"
  repo-url: https://github.com/MatthewBJane/artifact-corrections-for-effect-sizes/
  sharing: [twitter]
  downloads: [pdf]
  author:
  - name: "Matthew B. Jané"
    url: https://matthewbjane.com
  cover-image: figure/cover_photo.png
  chapters:
    - index.qmd
    - dedication.qmd
    - intro.qmd
    - part: "Artifact Corrections"
      chapters:
        - small_samples.qmd
        - unreliability.qmd
        - misclassification.qmd
        - artificial_dichotomization.qmd
        - scale_coarseness.qmd
        - direct_range_restriction.qmd
        - indirect_range_restriction.qmd
    - part: "Application to Meta-Analysis"
      chapters:
        - metaanalysis_intro.qmd
        - artifact_correction_metaanalysis.qmd
    - part: "References"
      chapters:
      - references_page.qmd
      
    
bibliography: references.bib
format:
  html:
    theme: lux
    linkcolor: '#a62675ff'
    title-block-banner: true
    title-block-style: default
    title-block-banner-color: white
    code-overflow: scroll
  pdf: 
    documentclass: book

citeproc: true

editor: visual

