project:
  type: book

book:
  favicon: figure/favicon_book.png
  title: "Artifact Corrections for Effect Sizes"
  twitter-card: true
  subtitle: "Implementation in R and Application to Meta-Analysis"
  page-navigation: true
  url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  date: 10/08/2023
  author:
  - name: "Matthew B. Jané"
    url: https://matthewbjane.com
    affiliation: University of Connecticut
  cover-image: figure/cover_photo.png
  chapters:
    - index.qmd
    - dedication.qmd
    - intro.qmd
    - part: "Artifact Corrections"
      chapters:
        - small_samples.qmd
        - unreliability.qmd
        - misclassification.qmd
        - artificial_dichotomization.qmd
        - scale_coarseness.qmd
        - direct_range_restriction.qmd
        - indirect_range_restriction.qmd
    - part: "Application to Meta-Analysis"
      chapters:
        - metaanalysis_intro.qmd
        - artifact_correction_metaanalysis.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme: lux
    linkcolor: '#a62675ff'
    title-block-banner: true
    title-block-style: default
    title-block-banner-color: white
    code-overflow: scroll
editor: visual

