project:
  type: book

book:
  title: "Correcting Effect Sizes for Statistical Artifacts"
  subtitle: "Implementation in R and Application to Meta-Analysis"
  page-navigation: true
  author: "Matthew B. Jané"
  date: "10/08/2023"
  chapters:
    - index.qmd
    - dedication.qmd
    - intro.qmd
    - part: "Artifact Corrections"
      chapters:
        - small_samples.qmd
        - unreliability.qmd
        - misclassification.qmd
        - artificial_dichotomization.qmd
        - scale_coarseness.qmd
        - direct_range_restriction.qmd
        - indirect_range_restriction.qmd
    - part: "Application to Meta-Analysis"
      chapters:
        - metaanalysis_intro.qmd
        - artifact_correction_metaanalysis.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: sandstone
    linkcolor: 'forestgreen'
  pdf:
    documentclass: scrreprt

editor: visual

