project:
  type: book
book:
  favicon: figure/favicon_book.png
  title: "Artifact Corrections for Effect Sizes"
  subtitle: "Implementation in R and Application to Meta-Analysis"
  twitter-card: 
    creator: "@MatthewBJane"
    image: figure/MJB_twitter.jpg
  page-navigation: true
  url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  site-url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  date: "10/08/2023"
  repo-url: https://github.com/MatthewBJane/artifact-corrections-for-effect-sizes/
  downloads: [pdf]
  author:
  - name: "Matthew B. Jané"
    url: https://matthewbjane.com
  cover-image: figure/MJB_cover.jpg
  chapters:
    - index.qmd
    - dedication.qmd
    - intro.qmd
    - part: "Artifact Corrections"
      chapters:
        - small_samples.qmd
        - unreliability.qmd
        - misclassification.qmd
        - artificial_dichotomization.qmd
        - scale_coarseness.qmd
        - direct_range_restriction.qmd
        - indirect_range_restriction.qmd
    - part: "Application to Meta-Analysis"
      chapters:
        - metaanalysis_intro.qmd
        - artifact_correction_metaanalysis.qmd
    - part: "References"
      chapters:
      - references_page.qmd
      
    
bibliography: references.bib
format:
  html:
    theme: lux
    linkcolor: '#a62675'
    title-block-banner: true
    title-block-style: default
    title-block-banner-color: white
    code-overflow: scroll
  pdf:
    code-block-bg: '#f5f7ff'
    code-block-border-left: false
    highlight-style: breeze
    mainfont: Times
    header-includes: |
      \titlehead{\includegraphics[width=7in]{figure/MJB_cover.jpg}}
  epub:
    cover-image: figure/MJB_cover.jpg

citeproc: true

editor: visual

