project:
  type: book

book:
  favicon: figure/favicon_book.png
  title: "Artifact Corrections for Effect Sizes"
  subtitle: "Seeing Reality for What it is"
  twitter-card:
    creator: "@MatthewBJane"
    image: figure/MJB_twitter.jpg
  page-navigation: true
  url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  site-url: https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/
  date: "04/24/2024"
  repo-url: https://github.com/MatthewBJane/artifact-corrections-for-effect-sizes/
  downloads: [pdf]
  sidebar:
    style: floating
  author:
  - name: "Matthew B. Jané"
    url: https://matthewbjane.com
  cover-image: figure/MJB_cover.jpg
  chapters:
    - index.qmd
    - "00-dedication/00-dedication.qmd"
    - "01-definitions/01-definitions.qmd"
    - "02-effect-sizes/02-effect-sizes.qmd"
    - "03-small-samples/03-small-samples.qmd"
    - part: "04-introduction-to-measurement-error/04-introduction-to-measurement-error.qmd"
      chapters:
        - "05-error-in-continuous-variables/05-error-in-continuous-variables.qmd"
        - "06-misclassification/06-misclassification.qmd"
        - "07-artificial-dichotomization/07-artificial-dichotomization.qmd"
        - "08-scale-coarseness/08-scale-coarseness.qmd"
    - part: "09-introduction-to-selection-effects/09-introduction-to-selection-effects.qmd"
      chapters:
        - "10-direct-selection/10-direct-selection.qmd"
        - "11-indirect-selection/11-indirect-selection.qmd"
    - "13-artifact-correction-meta-analysis/13-artifact-correction-meta-analysis.qmd"
    - "14-conclusion/14-conclusion.qmd"
    - "references/references_page.qmd"
      
    
bibliography: references.bib
format:
  html:
    theme: [zephyr,theme.scss]
    linkcolor: '#a62675'
    code-overflow: scroll
    comments:
      hypothesis: true
        
  # pdf:
  #   include-in-header:
  #     - text: |
  #         \usepackage{xcolor}
  #         \definecolor{rr}{HTML}{cb427b}
  #         \definecolor{gg}{HTML}{797979}
  #         \definecolor{bb}{HTML}{347e9f}
  #   code-block-bg: '#f5f7ff'
  #   code-block-border-left: false
  #   highlight-style: breeze
  #   mainfont: Times 
  #   fig-pos: "H"
  #   header-includes: |
  #     \titlehead{\includegraphics[width=7in]{figure/MJB_cover.jpg}}

citeproc: true

editor: visual

