<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Artifact Corrections for Effect Sizes - 7&nbsp; Artificial Dichotomization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./scale_coarseness.html" rel="next">
<link href="./misclassification.html" rel="prev">
<link href="./figure/favicon_book.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Artifact Corrections for Effect Sizes - 7&nbsp; Artificial Dichotomization">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/figure/MJB_twitter.jpg">
<meta name="twitter:creator" content="@MatthewBJane">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./small_samples.html">Artifact Corrections</a></li><li class="breadcrumb-item"><a href="./artificial_dichotomization.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artificial Dichotomization</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Artifact Corrections for Effect Sizes</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/MatthewBJane/artifact-corrections-for-effect-sizes/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Artifact-Corrections-for-Effect-Sizes.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Greetings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dedication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Dedication</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Effect Sizes and Artifacts</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Artifact Corrections</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Small Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unreliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Unreliability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./misclassification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Misclassification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./artificial_dichotomization.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artificial Dichotomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scale_coarseness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Scale Coarseness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./direct_range_restriction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Direct Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./indirect_range_restriction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Indirect Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Application to Meta-Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metaanalysis_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduction to Meta-Analysis Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./artifact_correction_metaanalysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Artifact Correction Meta-Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Conclusion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">References</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references_page.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">7.1</span> Introduction</a></li>
  <li><a href="#artificial-dichotomization-induced-measurement-error" id="toc-artificial-dichotomization-induced-measurement-error" class="nav-link" data-scroll-target="#artificial-dichotomization-induced-measurement-error"><span class="header-section-number">7.2</span> Artificial Dichotomization Induced Measurement Error</a></li>
  <li><a href="#correcting-correlations-for-artificial-dichotomization" id="toc-correcting-correlations-for-artificial-dichotomization" class="nav-link" data-scroll-target="#correcting-correlations-for-artificial-dichotomization"><span class="header-section-number">7.3</span> Correcting Correlations for Artificial Dichotomization</a>
  <ul class="collapse">
  <li><a href="#defining-the-target-quantity" id="toc-defining-the-target-quantity" class="nav-link" data-scroll-target="#defining-the-target-quantity"><span class="header-section-number">7.3.1</span> Defining the Target Quantity</a></li>
  <li><a href="#sec-corr-artifacts" id="toc-sec-corr-artifacts" class="nav-link" data-scroll-target="#sec-corr-artifacts"><span class="header-section-number">7.3.2</span> Artifact Correction for Correlations</a></li>
  </ul></li>
  <li><a href="#correcting-standardized-mean-differences-for-artificial-dichotomization" id="toc-correcting-standardized-mean-differences-for-artificial-dichotomization" class="nav-link" data-scroll-target="#correcting-standardized-mean-differences-for-artificial-dichotomization"><span class="header-section-number">7.4</span> Correcting Standardized Mean Differences for Artificial Dichotomization</a>
  <ul class="collapse">
  <li><a href="#defining-our-target-quantity" id="toc-defining-our-target-quantity" class="nav-link" data-scroll-target="#defining-our-target-quantity"><span class="header-section-number">7.4.1</span> Defining our Target Quantity</a></li>
  <li><a href="#sec-corr-smd" id="toc-sec-corr-smd" class="nav-link" data-scroll-target="#sec-corr-smd"><span class="header-section-number">7.4.2</span> Artifact Correction for Standardized Mean Differences</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-dichotomization" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artificial Dichotomization</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">7.1</span> Introduction</h2>
<p>Researchers occasionally split naturally continuous variables into two discrete groups to increase interpretability or conduct specific analyses (e.g., t-tests). However, artificially dichotomizing variables introduces measurement error variance thus attenuating effect size estimates <span class="citation" data-cites="hunter1990">Maxwell and Delaney (<a href="references_page.html#ref-maxwell1993" role="doc-biblioref">1993</a>)</span>. The obvious solution to this problem is to simply not dichotomize variables, however if only summary data is available to us, then we may not have this luxury. Dichotomization can also be practical in some instances. For example, clinical disorder diagnoses such as generalized anxiety disorder, are examples of dichotomization where individuals are separated into either having the disorder or not even though individual differences in anxiety exist as a continuum.</p>
</section>
<section id="artificial-dichotomization-induced-measurement-error" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="artificial-dichotomization-induced-measurement-error"><span class="header-section-number">7.2</span> Artificial Dichotomization Induced Measurement Error</h2>
<p>Variables that are dichotomized contain measurement error. This can be demonstrated by the simple fact that dichotomized scores are not perfectly correlated with their underlying continuous scores. To demonstrate this, we can draw a sample of scores and then split the data into high and low scorers and then calculate the correlation coefficient between the two (see <a href="#fig-dich">Figure&nbsp;<span>7.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dich" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="artificial_dichotomization_files/figure-html/fig-dich-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7.1: Visualizing the loss of precision when artificially dichotomizing. Left panel shows a normally distributed variable split (at the median/mean) into a high scoring group and a low scoring group.</figcaption>
</figure>
</div>
</div>
</div>
<p>Even with a perfectly reliable measure, dichotomization will introduce measurement error. Dichotomization occurs when data is split into two groups (low and high groups will be denoted as <span class="math inline">\(L\)</span> and <span class="math inline">\(H\)</span>, respectively) depending on whether they are above or below some cut-point <span class="math inline">\(C_X\)</span>. We can define artificially dichotomized scores as,</p>
<p><span class="math display">\[
X_D=
\begin{cases}
    H,&amp; \text{if } X\geq C_X\\
    L,&amp; \text{if } X&lt;C_X
\end{cases}
\]</span></p>
</section>
<section id="correcting-correlations-for-artificial-dichotomization" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="correcting-correlations-for-artificial-dichotomization"><span class="header-section-number">7.3</span> Correcting Correlations for Artificial Dichotomization</h2>
<section id="defining-the-target-quantity" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="defining-the-target-quantity"><span class="header-section-number">7.3.1</span> Defining the Target Quantity</h3>
<p>We want to obtain the population correlation between continuous scores of the independent (<span class="math inline">\(X\)</span>) and dependent variable (<span class="math inline">\(Y\)</span>), <span class="math inline">\(\rho_{XY}\)</span>.</p>
<p>There are two cases of dichotomization that may occur in a given study: the <em>univariate</em> case where only one variable (either <span class="math inline">\(X\)</span> <em>or</em> <span class="math inline">\(Y\)</span>) is dichotomized and the <em>bivariate</em> case where both variables are dichotomized. In either case, dichotomization will have a biasing effect on the study correlation coefficient. The study correlation on dichotomized data (using the bivariate case, <span class="math inline">\(r_{X_D Y_D}\)</span>) can be modeled as a function of the population correlation on continuous scores (<span class="math inline">\(\rho_{XY}\)</span>; i.e., the target), an artifact attenuation factor <span class="math inline">\(a\)</span>, and sampling error, <span class="math inline">\(e\)</span>,</p>
<p><span class="math display">\[
r_{X_DY_D} = a\rho_{XY}+e.
\]</span></p>
<p>An unbiased estimate of <span class="math inline">\(\rho_{XY}\)</span> can be calculated by dividing the study correlation by an estimate of the artifact attenuation factor, <span class="math inline">\(a\)</span>,</p>
<p><span class="math display">\[
r_{XY} = \frac{r_{X_D Y_D}}{a}.
\]</span></p>
</section>
<section id="sec-corr-artifacts" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="sec-corr-artifacts"><span class="header-section-number">7.3.2</span> Artifact Correction for Correlations</h3>
<p>Correlations can suffer from dichotomization in one variable (univariate case) or both variables (bivariate case). This section will discuss the procedure for obtaining an unbiased estimate of the correlation coefficient for both cases. For a comparative visualization of a correlation on with no dichotomization, univariate dichotomization, and bivariate dichotomization, see <a href="#fig-dich-cases">Figure&nbsp;<span>7.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dich-cases" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="artificial_dichotomization_files/figure-html/fig-dich-cases-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figure&nbsp;7.2: Scatter plots showing the correlation under dichotomization. The first panel (left to right) shows the correlation with no dichotomization (color and shapes of points denote where the split in the dichotomized cases will occur). The middle panel shows the univariate case where only the independent variable, <span class="math inline">\(X\)</span>, is dichotomized. The last panel shows the bivariate case where both independent (<span class="math inline">\(X\)</span>) and dependent (<span class="math inline">\(Y\)</span>) variables are dichotomized.</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-univariate-case" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="the-univariate-case">The Univariate Case</h4>
<p>In the simplest case of dichotomization, only one variable is dichotomized and the other is left continuous. A Pearson correlation computed between a dichotomous variable and a continuous variable is known as <em>point-biserial</em> correlation. However, if the variable is naturally continuous, we can estimate the correlation of the underlying continuous scores by computing a <em>biserial</em> correlation. If all we have access to is the dichotomized data, then we need to assume the shape of the underlying distribution, in this case, the biserial correlation assumes normality.</p>
<p>In the population, the study correlation <span class="math inline">\(\rho_{X_D Y}\)</span> is biased by some artifact biasing factor, <span class="math inline">\(a\)</span>,</p>
<p><span class="math display">\[
\rho_{X_D Y} = a\rho_{XY}.
\]</span></p>
<p>To estimate the attenuation factor <span class="math inline">\(a\)</span>, we must first figure out where the split of the data occured. To do this, we must first calculate the proportion of the sample in the assigned to the low or high scoring group:</p>
<p><span class="math display">\[
p_X  := p(X_i \geq C_X) = \frac{ n_{\text{H}} }{n_{\text{H}} + n_{\text{L}}}
\]</span></p>
<p>or</p>
<p><span class="math display">\[
p_X := p(X_i &lt; C_X) = \frac{ n_{\text{L}} }{n_{\text{H}} + n_{\text{L}}}.
\]</span></p>
<p>Where <span class="math inline">\(n\)</span> indicates the sample size within the low, <span class="math inline">\(L\)</span>, and high, <span class="math inline">\(H\)</span>, scoring groups.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>It will not matter whether you calculate the proportion of the sample in the high scoring group or the low scoring group for <span class="math inline">\(p_X\)</span>. Once you decide on one, do not change it.</p>
</div>
</div>
<p>We can use the quantile function (<span class="math inline">\(\phi^{-1}[\cdot]\)</span>, i.e., the inverse of the cumulative density of the standard normal distribution) to find where the split would have occured on a standard normal distribution, <span class="math inline">\(s_X=\phi^{-1}[p_X]\)</span>. Using the location of the split on the standard normal, we can compute the artifact attenuation factor [an adaptation of equation 2, <span class="citation" data-cites="hunter1990">Hunter and Schmidt (<a href="references_page.html#ref-hunter1990" role="doc-biblioref">1990</a>)</span>],</p>
<p><span id="eq-artifact-factor-dich"><span class="math display">\[
\hat{a} =\frac{\varphi\left(s_X\right)}{\sqrt{p_X(1-p_X)}}.
\tag{7.1}\]</span></span></p>
<p>Where <span class="math inline">\(\varphi(\cdot)\)</span> is the normal ordinate function (i.e., probability density function of a standard normal distribution). <a href="#fig-normal-density">Figure&nbsp;<span>7.3</span></a> visually demonstrates how each of these relate to a standard normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normal-density" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="artificial_dichotomization_files/figure-html/fig-normal-density-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7.3: This figure shows a normal distribution of scores split into a high scoring and low scoring group. The cut-point of the standard normal distribution is computed with the quantile function, <span class="math inline">\(\phi^{-1}[p_X]\)</span>. The ordinate of the normal distribution at that cut-point is calculated with the normal ordinate function, <span class="math inline">\(\varphi\left(\phi^{-1}[p_X]\right)\)</span>.</figcaption>
</figure>
</div>
</div>
</div>
<p>In the case of a median split, where the cut-point would be placed at zero of a standard normal (splitting the distribution in equal halves), the attenuation factor would simplify to <span class="math inline">\(\hat{a} =\frac{\varphi(0)}{\sqrt{.5(.5)}}\)</span> <span class="math inline">\(=\frac{2}{\sqrt{2\pi}}\)</span>.</p>
<p>We can correct the study correlation using the estimated artifact factor, <span class="math inline">\(\hat{a}\)</span>, therefore the full correction equation is,</p>
<p><span id="eq-dich-r"><span class="math display">\[
r_{XY} = \frac{r_{X_DY}}{\hat{a}} = \frac{r_{X_DY}}{\left[\frac{\varphi\left(s_X\right)}{\sqrt{p_X(1-p_X)}}\right]}.
\tag{7.2}\]</span></span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Converting to <span class="math inline">\(\boldsymbol{\mathsf{r_{X_{D}Y}}}\)</span> from means and standard deviations
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is common that studies do not report the correlation between dichotomized and continuous scores, <span class="math inline">\(r_{X_DY}\)</span> (i.e., the point-biserial correlation), instead they may report the means and standard deviations instead. To obtain the point-biserial correlation, <span class="math inline">\(r_{X_D Y}\)</span>, we need the the mean of the high scoring group (<span class="math inline">\(\overline{Y}_H\)</span>), mean of the low scoring groups (<span class="math inline">\(\overline{Y}_L\)</span>), the standard deviation across all individuals (<span class="math inline">\(S_Y\)</span>; not to be confused with the pooled/average standard deviation within each group), and the sample sizes within each group (<span class="math inline">\(n_H\)</span> and <span class="math inline">\(n_L\)</span>) to calculate <span class="math inline">\(r_{X_DY}\)</span>,</p>
<p><span class="math display">\[
r_{X_D Y} =\frac{\overline{Y}_H-\overline{Y}_L}{S_Y} \sqrt{p_X(1-p_X)}.
\]</span></p>
<p>If the standard deviations are reported only for within the high and low groups, you can estimate the total standard deviation with the following formula,</p>
<p><span class="math display">\[
S_X = \sqrt{\frac{n_HS_{X_H} + n_L S_{X_L}}{n_H + n_L} +\frac{n_Hn_L}{n_H + n_L}(\overline{X}_H - \overline{X}_L)^2}.
\]</span></p>
</div>
</div>
<p><span class="citation" data-cites="hunter1990">Hunter and Schmidt (<a href="references_page.html#ref-hunter1990" role="doc-biblioref">1990</a>)</span> suggested that one should correct the standard error by dividing the uncorrected standard error by the artifact attenuation factor <span class="citation" data-cites="hunter1990">(see equation 6, <a href="references_page.html#ref-hunter1990" role="doc-biblioref">Hunter and Schmidt 1990</a>)</span>. However simulations have found that this computation does not work as well as Soper’s exact method <span class="citation" data-cites="soper1914 jacobs2017">(<a href="references_page.html#ref-soper1914" role="doc-biblioref">Soper 1914</a>; <a href="references_page.html#ref-jacobs2017" role="doc-biblioref">Jacobs and Viechtbauer 2017</a>)</span>. Therefore the standard error of the corrected (biserial) correlation can be estimated with the following formula <span class="citation" data-cites="jacobs2017">(equation 12, <a href="references_page.html#ref-jacobs2017" role="doc-biblioref">Jacobs and Viechtbauer 2017</a>)</span>,</p>
<p><span class="math display">\[
\small{se(r_{XY}) = \sqrt{\frac{1}{n-1} \left(r_{XY}^4+r_{XY}^2\left(\frac{p_X(1-p_X)s_X^2}{\varphi\left(s_X\right)^2} + \frac{2p_X - 1}{\varphi\left(s_X\right)} -\frac{5}{2}\right)+\frac{p_X(1-p_X)}{\varphi\left(s_X\right)^2}\right)}}.
\]</span></p>
<p><span class="citation" data-cites="soper1914">Soper (<a href="references_page.html#ref-soper1914" role="doc-biblioref">1914</a>)</span> also developed an approximation of the above formula,</p>
<p><span class="math display">\[
se(r_{XY}) \approx \sqrt{\frac{1}{n-1}} \left(\frac{\sqrt{p_X(1-p_X)}}{\varphi\left(s_X\right)}-r_{XY}^2\right).
\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Applied Example in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s say we want to assess the relationship between a sales person’s score on a job knowledge test and their job performance estimated as the number of sales made per week. However the researchers of the study chose to dichotomize sales people into high sales performers and low sales performers by splitting the sample into two equally sized groups. They then reported the means and standard deviations of job knowledge test scores of both groups:</p>
<ol type="1">
<li>Low sales performers: Mean = 22 (SD = 4, n = 50)</li>
<li>High sales performers: Mean = 24 (SD = 4, n = 50)</li>
</ol>
<p>To calculate the corrected correlation we can use <code>escalc()</code> function from the <code>metafor</code> package <span class="citation" data-cites="viechtbauer2010">(<a href="references_page.html#ref-viechtbauer2010" role="doc-biblioref">Viechtbauer 2010</a>)</span>. Using the argument <code>measure='RBIS'</code> will return the biserial correlation coefficient which is equivalent to the corrected correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">'RBIS'</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">m1i =</span> <span class="dv">24</span>, <span class="co"># High performer mean </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">m2i =</span> <span class="dv">22</span>, <span class="co"># Low performer mean</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">sd1i =</span> <span class="dv">4</span>, <span class="co"># High performer SD</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">sd2i =</span> <span class="dv">4</span>, <span class="co"># Low performer SD</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">n1i =</span> <span class="dv">50</span>, <span class="co"># High performer sample size</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">n2i =</span> <span class="dv">50</span>, <span class="co"># Low performer sample size</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.names =</span> <span class="fu">c</span>(<span class="st">'rXY'</span>,<span class="st">'se.2'</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    rXY  se.2 
1 0.307 0.014 </code></pre>
</div>
</div>
<p>Therefore the estimated correlation on continuous scores is <span class="math inline">\(r_{XY}=.31\)</span>.</p>
<p>If the study reported a Pearson correlation (point-biserial) between the dichotomized variable and the continuous variable of <span class="math inline">\(r_{X_D Y}=.245\)</span>, then</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psychmeta)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">correct_r_dich</span>(<span class="at">r =</span> .<span class="dv">245</span>, <span class="co"># study point-biserial correlation</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">px =</span> .<span class="dv">50</span>, <span class="co"># proportion of sample in low or high group</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">n =</span> <span class="dv">100</span>) <span class="co"># total sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  r_corrected var_e_corrected    n_adj
1    0.307062      0.01401901 59.51455</code></pre>
</div>
</div>
<p>The corrected correlation for continuous scores is equal to the calculation using the means and standard deviations. Note that the estimated sampling variance of the corrected correlation, <code>se.2</code> (in the <code>psychmeta</code> example) and <code>var_e_corrected</code> (in the <code>metafor</code> example), are both equal to the squared corrected standard error (<span class="math inline">\(se(r_{XY})^2\)</span>).</p>
</div>
</div>
</section>
<section id="the-bivariate-case" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="the-bivariate-case">The Bivariate Case</h4>
<p>In some cases, both independent and dependent variables are dichotomized. A Pearson correlation calculated on these two dichotomized (binary) variables would be equal to the phi coefficient (or also known as Matthew’s correlation coefficient) and we can denote it with our notation for dichotomized variables, <span class="math inline">\(\rho_{X_D X_D}\)</span>. Dichotomized data can be structured in a contingency table (see <a href="#tbl-biv-dich">Table&nbsp;<span>7.1</span></a>).</p>
<div class="columns">
<div class="column" style="width:25%;">

</div><div class="column" style="width:50%;">
<div id="tbl-biv-dich" class="anchored">
<table class="table-hover table">
<caption>Table&nbsp;7.1: Contingency table.</caption>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(X_D=\text{Low}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(X_D=\text{High}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(Y_D=\text{Low}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{LL}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{HL}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(Y_D=\text{High}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{LH}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_{HH}\)</span></td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:25%;">

</div>
</div>
<p><a href="#fig-biv-dich">Figure&nbsp;<span>7.4</span></a> illustrates how this contingency table relates to an underlying continuous bivariate normal distribution.</p>
<div id="fig-biv-dich" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figure/diagram-dich.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7.4: The ellipse indicates the bivariate normal distribution of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> with a strong positive correlation. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are positively correlated then we should more individuals populating the high-high and low-low cells rather than the high-low and low-high cells which can be seen by the area of the ellipse located in each quadrant.</figcaption>
</figure>
</div>
<p>The corrected correlation coefficient for two dichotomized variables is commonly referred to as the tetrachoric correlation coefficient. The tetrachoric correlation estimates the correlation on continuous scores assuming a bivariate normal distribution.</p>
<p>One of the difficulties of computing a dichotomization corrected (tetrachoric) correlation (<span class="math inline">\(r_{XY}\)</span>) is that the relationship between binary variables are reported in different ways across studies, we will describe how to obtain a dichtomization corrected correlation in four different cases:</p>
<ol type="1">
<li>The full contingency table is provided, including the sample sizes for each cell.</li>
<li>The odds ratio is reported as well as the marginal proportions (proportions in low and high groups for each variable).</li>
<li>The Phi coefficient is reported.</li>
</ol>
<section id="case-1-full-contingency-table-is-reported" class="level5 unnumbered" style="color:#555555">
<h5 class="unnumbered anchored" style="color:#555555" data-anchor-id="case-1-full-contingency-table-is-reported">Case 1: Full contingency table is reported</h5>
<p>If the full contingency table is reported, then the tetrachoric correlation can be calculated directly. Due to the complexity of the calculation, we will use R.</p>
<p>The <code>escalc()</code> function in the <code>metafor</code> package <span class="citation" data-cites="viechtbauer2010">(<a href="references_page.html#ref-viechtbauer2010" role="doc-biblioref">Viechtbauer 2010</a>)</span> can take on values from a contingency table and compute a tetrachoric correlation using the <code>measure='RTET'</code> argument. The function uses the method described by <span class="citation" data-cites="kirk1973">Kirk (<a href="references_page.html#ref-kirk1973" role="doc-biblioref">1973</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example Contingency Table</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#    XL   XH</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># YL 43   23</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># YH 27   38  </span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">'RTET'</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">ai =</span> <span class="dv">43</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">bi =</span> <span class="dv">23</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">ci =</span> <span class="dv">27</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">di =</span> <span class="dv">38</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.names =</span> <span class="fu">c</span>(<span class="st">'rXY'</span>,<span class="st">'se.2'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     rXY   se.2 
1 0.3637 0.0155 </code></pre>
</div>
</div>
<p>The results show a dichotomization corrected correlation of <span class="math inline">\(r_{XY} = .36\)</span> and an estimated sampling variance of <span class="math inline">\(se_c^2=.016\)</span>.</p>
</section>
<section id="case-2-odds-ratio-is-reported" class="level5 unnumbered" style="color:#555555">
<h5 class="unnumbered anchored" style="color:#555555" data-anchor-id="case-2-odds-ratio-is-reported">Case 2: odds ratio is reported</h5>
<p>If the odds ratio is all that is available, then we can use the tetrachoric correlation approximation described by <span class="citation" data-cites="bonett2005">Bonett and Price (<a href="references_page.html#ref-bonett2005" role="doc-biblioref">2005</a>)</span>. Using the estimated odds ratio (<span class="math inline">\(OR=(n_{HH}n_{LL})/(n_{HL}n_{LH})\)</span>) and the marginal proportions (<span class="math inline">\(p_X\)</span> and <span class="math inline">\(p_Y\)</span>; for this case, both proportions should be with respect to the high scoring group) we can approximate the dichotomization corrected (tetrachoric) correlation <span class="citation" data-cites="bonett2005">(see equation 4, <a href="references_page.html#ref-bonett2005" role="doc-biblioref">Bonett and Price 2005</a>)</span>,</p>
<p><span class="math display">\[
r_{XY} \approx \cos\left( \frac{\pi}{1+OR^\Omega}\right)
\]</span> Where <span class="math inline">\(\Omega\)</span> is</p>
<p><span class="math display">\[
\Omega = 1 - \frac{\left|p_X -p_Y\right|}{5} - \left[\frac{1}{2}-\min(p_X,p_Y)\right]^2.
\]</span></p>
<p>Note that <span class="math inline">\(\min(p_X,p_Y)\)</span> is the smallest marginal proportion. The standard error of the estimated correlation can be computed with the following formula [see equation 9, <span class="citation" data-cites="bonett2005">Bonett and Price (<a href="references_page.html#ref-bonett2005" role="doc-biblioref">2005</a>)</span>; note this equation is slightly changed in order to account for the fact that we only have access to the marginal sample sizes and proportions]</p>
<p><span class="math display">\[
\small{se(r_{XY}) =  \frac{\pi\times \Omega\times OR^\Omega\times\sin\left(\frac{\pi}{1+OR^\Omega}\right)}{\left(1+OR^\Omega\right)^2}\times\sqrt{\frac{4}{n}}}
\]</span></p>
<p>Where <span class="math inline">\(n\)</span> is the total sample size. Using base R, we can convert the odds ratio to a tetrachoric correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>pX <span class="ot">&lt;-</span> .<span class="dv">4</span> <span class="co"># proportion of individuals in high group in XD</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>pY <span class="ot">&lt;-</span> .<span class="dv">5</span> <span class="co"># proportion of individuals in high group in YD</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">150</span> <span class="co"># total sample size</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fl">1.43</span> <span class="co"># odds ratio</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>omega <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">abs</span>(pX<span class="sc">-</span>pY) <span class="sc">/</span> <span class="dv">5</span> <span class="sc">-</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span> <span class="fu">min</span>(<span class="fu">c</span>(pX,pY)))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate corrected correlation</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>rXY <span class="ot">&lt;-</span> <span class="fu">cos</span>(pi<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>OR<span class="sc">^</span>omega))</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate standard error</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> pi<span class="sc">*</span>omega<span class="sc">*</span>OR<span class="sc">^</span>omega<span class="sc">*</span><span class="fu">sin</span>(pi<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>OR<span class="sc">^</span>omega)) <span class="sc">/</span> (<span class="dv">1</span><span class="sc">+</span>OR<span class="sc">^</span>omega)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">4</span><span class="sc">/</span>n)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(rXY, se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           rXY      se
[1,] 0.2665276 0.11637</code></pre>
</div>
</div>
</section>
<section id="case-3-correlation-between-dichotomized-variables" class="level5 unnumbered" style="color:#555555">
<h5 class="unnumbered anchored" style="color:#555555" data-anchor-id="case-3-correlation-between-dichotomized-variables">Case 3: Correlation between dichotomized variables</h5>
<p>A Pearson correlation coefficient calculated between two binary variables is most commonly referred to as a Phi coefficient or Matthew’s correlation coefficient. However, the Phi coefficient underestimates the correlation on the underlying continuous scores (assuming bivariate normality). Therefore we can approximate the correlation on continuous scores by using a similar correction to the univariate case. We can define an artifact attenuation factor that is similar to <a href="#eq-artifact-factor-dich">Equation&nbsp;<span>7.1</span></a>, but with the added attenuation of <span class="math inline">\(Y_D\)</span>,</p>
<p><span class="math display">\[
\hat{a} =\left[\frac{\varphi\left(\phi^{-1}[p_X]\right)}{\sqrt{p_X(1-p_X)}}\right]\times\left[\frac{\varphi\left(\phi^{-1}[p_Y]\right)}{\sqrt{p_Y(1-p_Y)}}\right].
\]</span></p>
<p>Therefore we can correct <span class="math inline">\(r_{X_DY_D}\)</span> for dichotomization in both variables by dividing by the attenuation factor, <span class="math display">\[
r_{XY} = \frac{r_{X_DY_D}}{\hat{a}}=\frac{r_{X_DY_D}}{\left[\frac{\varphi\left(\phi^{-1}[p_X]\right)}{\sqrt{p_X(1-p_X)}}\right]\times\left[\frac{\varphi\left(\phi^{-1}[p_Y]\right)}{\sqrt{p_Y(1-p_Y)}}\right]}
\]</span> This correction is only an approximation, however it performs fairly well when the correlation is below .8 <span class="citation" data-cites="hunter1990">(<a href="references_page.html#ref-hunter1990" role="doc-biblioref">Hunter and Schmidt 1990</a>)</span>. The standard error of the corrected correlation can be calculated similarly <span class="citation" data-cites="hunter1990">(adaptation of equation 9, <a href="references_page.html#ref-hunter1990" role="doc-biblioref">Hunter and Schmidt 1990</a>)</span>,</p>
<p><span class="math display">\[
se(r_{XY})=\frac{se(r_{X_DY_D})}{\left[\frac{\varphi\left(\phi^{-1}[p_X]\right)}{\sqrt{p_X(1-p_X)}}\right]\times\left[\frac{\varphi\left(\phi^{-1}[p_Y]\right)}{\sqrt{p_Y(1-p_Y)}}\right]}
\]</span></p>
<p>Using the <code>correct_r_dich()</code> function in the <code>psychmeta</code> package <span class="citation" data-cites="dahlke2019">(<a href="references_page.html#ref-dahlke2019" role="doc-biblioref">Dahlke and Wiernik 2019</a>)</span>, we can correct the observed study correlation for dichotomization.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psychmeta)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">correct_r_dich</span>(<span class="at">r =</span> .<span class="dv">20</span>,  <span class="co"># observed study correlation</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">px =</span> .<span class="dv">50</span>, <span class="co"># proportion of sample in high group of XD</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">py =</span> .<span class="dv">50</span>, <span class="co"># proportion of sample in high group of YD</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">n =</span> <span class="dv">100</span>)  <span class="co"># sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  r_corrected var_e_corrected    n_adj
1   0.3141593      0.02296926 36.36678</code></pre>
</div>
</div>
<p>The output shows the corrected correlation to be <span class="math inline">\(r_{XY}=.31\)</span> and it’s estimated sampling variance <span class="math inline">\(se_c^2=.023\)</span>.</p>
</section>
</section>
</section>
</section>
<section id="correcting-standardized-mean-differences-for-artificial-dichotomization" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="correcting-standardized-mean-differences-for-artificial-dichotomization"><span class="header-section-number">7.4</span> Correcting Standardized Mean Differences for Artificial Dichotomization</h2>
<section id="defining-our-target-quantity" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="defining-our-target-quantity"><span class="header-section-number">7.4.1</span> Defining our Target Quantity</h3>
<p>The target quantity is the standardized mean difference between groups of a naturally continuous variable. Our target can thus be defined as the population standardized mean difference between groups <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> on continuous scores of the dependent variable, <span class="math inline">\(\delta_{gY}\)</span>. For a given study the dichotomized standardized mean difference (<span class="math inline">\(d_{gY_D}\)</span>) can be defined as</p>
<p><span class="math display">\[
d_{gY_D} = a\delta_{gY} + e
\]</span></p>
<p>Therefore to obtain an unbiased estimate of the target quantity, we can correct the observed study standardized mean difference by dividing by the attenuation factor,</p>
<p><span class="math display">\[
d_{gY} = \frac{d_{gY_D}}{\hat{a}}
\]</span></p>
</section>
<section id="sec-corr-smd" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="sec-corr-smd"><span class="header-section-number">7.4.2</span> Artifact Correction for Standardized Mean Differences</h3>
<p>The simplest way to correct for dichotomization in a standardized mean difference is to first convert the observed <span class="math inline">\(d\)</span> value of the dichotomized dependent variable to a correlation coefficient. When converting to a correlation coefficient, it’s important to note the binary nature of both variables, leading us to estimate the phi coefficient rather than the point-biserial correlation that we would be estimating if the dependent variable was continuous. To calculate the phi coefficient from a <span class="math inline">\(d\)</span> value we can use the proportion of group membership in group <span class="math inline">\(A\)</span> or group <span class="math inline">\(B\)</span> (<span class="math inline">\(p_g\)</span>; it does not matter which one is chosen, as long as it is consistent for every instance of <span class="math inline">\(p_g\)</span>),</p>
<p><span class="math display">\[
r_{gY_D} = \frac{d_{gY_D}}{\sqrt{d_{gY_D}^2+\frac{1}{p(1-p)}}}
\]</span></p>
<p>We can then correct the correlation similar to how we did in <a href="#sec-corr-artifacts"><span>Section&nbsp;7.3.2</span></a>,</p>
<p><span class="math display">\[
r_{gY} = \frac{r_{gY_D}}{\left[\frac{\varphi\left(\phi^{-1}[p_Y]\right)}{\sqrt{p_Y(1-p_Y)}}\right]}.
\]</span></p>
<p>Then we can convert the corrected correlation back into a standardized mean difference,</p>
<p><span class="math display">\[
d_{gY} = \frac{r_{gY}}{\sqrt{p_g\left(1-p_g\right)\left(1-r_{gY}^2\right)}}.
\]</span></p>
<p>Where <span class="math inline">\(d_{gY}\)</span> is our corrected correlation (i.e., the estimated correlation on continuous variables). The observed sampling variance must also be corrected using the same three step procedure. For simplicity, we will consolidate this into one formula,</p>
<p><span class="math display">\[
se(d_{gY}) = \frac {se(d_{gY_D}) \times r_{XY}} {r_{x_DY_D}\sqrt{\left(1+d_{gY_D}^2p_g[1-p_g]\right)^3(1-r_{gY}^2)^3}}.
\]</span></p>
<section id="obtaining-standardized-mean-difference-from-odds-ratio" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="obtaining-standardized-mean-difference-from-odds-ratio">Obtaining Standardized Mean Difference from Odds Ratio</h4>
<p>In most cases, difference in dichotomized outcomes between two groups is unlikely to be reported as a standardized mean difference, instead it will be more commonly reported as an odds ratio (<span class="math inline">\(OR\)</span>). The odds ratio is asymmetric about 1 (i.e., the null), but we can make it symmetric by log transforming it (<span class="math inline">\(\log(OR)\)</span>). The standard error of the log odds ratio can be defined as,</p>
<p><span class="math display">\[
se(\log(OR)) = \sqrt{\frac{1}{n_{AH}} + \frac{1}{n_{AL}} + \frac{1}{n_{BH}} + \frac{1}{n_{BL}}}
\]</span></p>
<p>The equation above requires the full contingency table to compute. From there we can use the cox-logit method to convert the odds ratio to a standardized mean difference <span class="citation" data-cites="cox1989 haddock1998">(<a href="references_page.html#ref-cox1989" role="doc-biblioref">Cox 1989</a>; <a href="references_page.html#ref-haddock1998" role="doc-biblioref">Haddock, Rindskopf, and Shadish 1998</a>)</span>. Them method is quite simple as it just divides the log odds ratio by 1.65,</p>
<p><span id="eq-or-d"><span class="math display">\[
d_{gY} = \frac{\log(OR)}{1.65}
\tag{7.3}\]</span></span></p>
<p>and the corresponding sampling variance of the <span class="math inline">\(d\)</span> value is,</p>
<p><span class="math display">\[
se(d_{gY}) = \frac{se(\log(OR))}{1.65}.
\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Applied Example in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s consider a hypothetical scenario where we want to examine the relationship between caffeine consumption and the occurrence of heart palpitations in a population. Our target quantity in this case is the standardized mean difference of coffee consuption between people with and without heart palpitations. The variable of interest, caffeine consumption, is continuous (measured in milligrams per day). However, the researcher decides to dichotomize this variable into two groups: “High Caffeine Consumers” and “Low Caffeine Consumers.”</p>
<p>Suppose we have a sample of 500 individuals, and we dichotomize their caffeine consumption into “High Caffeine Consumers” (more than 250mg per day) and “Low Caffeine Consumers” (less than or equal to 250mg per day). We also observe the occurrence of heart palpitations in these individuals.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Heart Palpitations: Yes</th>
<th style="text-align: center;">Heart Palpitations: No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High Consumers</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">140</td>
</tr>
<tr class="even">
<td>Low Consumers</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">280</td>
</tr>
</tbody>
</table>
<p>We can calculate the dichotomization corrected standardized mean difference by calculating the log odds ratio with <code>escalc()</code> function and then applying <a href="#eq-or-d">Equation&nbsp;<span>7.3</span></a> to estimate <span class="math inline">\(d_{gY}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate log-odds ratio</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">'OR'</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">ai =</span> <span class="dv">60</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">bi =</span> <span class="dv">140</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ci =</span> <span class="dv">20</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">di =</span> <span class="dv">280</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">var.names =</span> <span class="fu">c</span>(<span class="st">'logOR'</span>,<span class="st">'se.2'</span>))  </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to standardized mean difference</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>dgY <span class="ot">&lt;-</span> OR<span class="sc">$</span>logOR <span class="sc">/</span> <span class="fl">1.65</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(OR<span class="sc">$</span>se<span class="fl">.2</span>) <span class="sc">/</span> <span class="fl">1.65</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(dgY,se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          dgY        se
[1,] 1.085915 0.1685905</code></pre>
</div>
</div>
<p>We can see that the standardized mean difference is estimated to be <span class="math inline">\(d_{gY}=1.09\)</span> and the corrected standard error is <span class="math inline">\(se_c=.169\)</span></p>
</div>
</div>
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="matthewbjane" data-description="Support me on Buy me a coffee!" data-message="Thank you for being here." data-color="#eeb4d7ff" data-position="Right" data-x_margin="18" data-y_margin="18"></script>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bonett2005" class="csl-entry" role="listitem">
Bonett, Douglas G., and Robert M. Price. 2005. <span>“Inferential Methods for the Tetrachoric Correlation Coefficient.”</span> <em>Journal of Educational and Behavioral Statistics</em> 30 (2): 213–25. <a href="https://www.jstor.org/stable/3701350">https://www.jstor.org/stable/3701350</a>.
</div>
<div id="ref-cox1989" class="csl-entry" role="listitem">
Cox, D. R. 1989. <em>Analysis of Binary Data</em>. 2nd ed. New York: Routledge. <a href="https://doi.org/10.1201/9781315137391">https://doi.org/10.1201/9781315137391</a>.
</div>
<div id="ref-dahlke2019" class="csl-entry" role="listitem">
Dahlke, Jeffrey A., and Brenton M. Wiernik. 2019. <span>“Psychmeta: An R Package for Psychometric Meta-Analysis.”</span> <em>Applied Psychological Measurement</em> 43 (5): 415–16. <a href="https://doi.org/10.1177/0146621618795933">https://doi.org/10.1177/0146621618795933</a>.
</div>
<div id="ref-haddock1998" class="csl-entry" role="listitem">
Haddock, C. Keith, David Rindskopf, and William R. Shadish. 1998. <span>“Using Odds Ratios as Effect Sizes for Meta-Analysis of Dichotomous Data: A Primer on Methods and Issues.”</span> <em>Psychological Methods</em> 3 (3): 339–53. <a href="https://doi.org/10.1037/1082-989X.3.3.339">https://doi.org/10.1037/1082-989X.3.3.339</a>.
</div>
<div id="ref-hunter1990" class="csl-entry" role="listitem">
Hunter, John, and Frank Schmidt. 1990. <span>“Dichotomization of Continuous Variables: The Implications for Meta-Analysis.”</span> <em>Journal of Applied Psychology</em> 75 (June): 334–49. <a href="https://doi.org/10.1037/0021-9010.75.3.334">https://doi.org/10.1037/0021-9010.75.3.334</a>.
</div>
<div id="ref-jacobs2017" class="csl-entry" role="listitem">
Jacobs, Perke, and Wolfgang Viechtbauer. 2017. <span>“Estimation of the Biserial Correlation and Its Sampling Variance for Use in Meta-Analysis.”</span> <em>Research Synthesis Methods</em> 8 (2): 161–80. <a href="https://doi.org/10.1002/jrsm.1218">https://doi.org/10.1002/jrsm.1218</a>.
</div>
<div id="ref-kirk1973" class="csl-entry" role="listitem">
Kirk, David B. 1973. <span>“On the Numerical Approximation of the Bivariate Normal (Tetrachoric) Correlation Coefficient.”</span> <em>Psychometrika</em> 38 (2): 259–68. <a href="https://doi.org/10.1007/BF02291118">https://doi.org/10.1007/BF02291118</a>.
</div>
<div id="ref-maxwell1993" class="csl-entry" role="listitem">
Maxwell, Scott, and Harold Delaney. 1993. <span>“Bivariate Median Splits and Spurious Statistical Significance.”</span> <em>Psychological Bulletin</em> 113 (January): 181–90. <a href="https://doi.org/10.1037/0033-2909.113.1.181">https://doi.org/10.1037/0033-2909.113.1.181</a>.
</div>
<div id="ref-soper1914" class="csl-entry" role="listitem">
Soper, H. E. 1914. <span>“On the Probable Error of the Bi-Serial Expression for the Correlation Coefficient.”</span> <em>Biometrika</em> 10 (2/3): 384–90. <a href="https://doi.org/10.2307/2331789">https://doi.org/10.2307/2331789</a>.
</div>
<div id="ref-viechtbauer2010" class="csl-entry" role="listitem">
Viechtbauer, Wolfgang. 2010. <span>“Conducting meta-analyses in R with the metafor package.”</span> <em>Journal of Statistical Software</em> 36 (3): 1–48. <a href="https://doi.org/10.18637/jss.v036.i03">https://doi.org/10.18637/jss.v036.i03</a>.
</div>
</div>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./misclassification.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Misclassification</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./scale_coarseness.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Scale Coarseness</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>