<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Artifact Corrections for Effect Sizes - 5&nbsp; Unreliability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./misclassification.html" rel="next">
<link href="./small_samples.html" rel="prev">
<link href="./figure/favicon_book.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
      }
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Artifact Corrections for Effect Sizes - 5&nbsp; Unreliability">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/figure/unreliability_diagram_1.png">
<meta name="twitter:creator" content="@MatthewBJane">
<meta name="twitter:image-height" content="1017">
<meta name="twitter:image-width" content="1372">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./small_samples.html">Artifact Corrections</a></li><li class="breadcrumb-item"><a href="./unreliability.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Unreliability</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Unreliability</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Artifact Corrections for Effect Sizes</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/MatthewBJane/artifact-corrections-for-effect-sizes/tree/gh-pages" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Artifact-Corrections-for-Effect-Sizes.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <a href="https://twitter.com/intent/tweet?url=|url|" title="Twitter" class="quarto-navigation-tool px-1" aria-label="Twitter"><i class="bi bi-twitter"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Greetings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dedication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Dedication</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Effect Sizes and Notation</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Artifact Corrections</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./small_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Small Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unreliability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Unreliability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./misclassification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Misclassification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./artificial_dichotomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artificial Dichotomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scale_coarseness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Scale Coarseness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./direct_range_restriction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Direct Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./indirect_range_restriction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Indirect Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Application to Meta-Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metaanalysis_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduction to Meta-Analysis Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./artifact_correction_metaanalysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Artifact Correction Meta-Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">References</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references_page.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#sec-true-score-theory" id="toc-sec-true-score-theory" class="nav-link" data-scroll-target="#sec-true-score-theory"><span class="header-section-number">5.2</span> Reliability in True Score Theory</a></li>
  <li><a href="#reliability-vs-validity" id="toc-reliability-vs-validity" class="nav-link" data-scroll-target="#reliability-vs-validity"><span class="header-section-number">5.3</span> Reliability vs Validity</a></li>
  <li><a href="#estimating-reliability" id="toc-estimating-reliability" class="nav-link" data-scroll-target="#estimating-reliability"><span class="header-section-number">5.4</span> Estimating Reliability</a>
  <ul class="collapse">
  <li><a href="#internal-consistency-estimators" id="toc-internal-consistency-estimators" class="nav-link" data-scroll-target="#internal-consistency-estimators"><span class="header-section-number">5.4.1</span> Internal Consistency Estimators</a></li>
  <li><a href="#calculating-internal-consistency-in-r" id="toc-calculating-internal-consistency-in-r" class="nav-link" data-scroll-target="#calculating-internal-consistency-in-r"><span class="header-section-number">5.4.2</span> Calculating Internal Consistency in R</a></li>
  <li><a href="#test-retest-stability-estimator" id="toc-test-retest-stability-estimator" class="nav-link" data-scroll-target="#test-retest-stability-estimator"><span class="header-section-number">5.4.3</span> Test-Retest Stability Estimator</a></li>
  <li><a href="#calculating-test-retest-reliability-in-r" id="toc-calculating-test-retest-reliability-in-r" class="nav-link" data-scroll-target="#calculating-test-retest-reliability-in-r"><span class="header-section-number">5.4.4</span> Calculating Test-Retest Reliability in R</a></li>
  <li><a href="#sec-sources" id="toc-sec-sources" class="nav-link" data-scroll-target="#sec-sources"><span class="header-section-number">5.4.5</span> Sources of Measurement Error</a></li>
  </ul></li>
  <li><a href="#correction-for-bias-in-correlations" id="toc-correction-for-bias-in-correlations" class="nav-link" data-scroll-target="#correction-for-bias-in-correlations"><span class="header-section-number">5.5</span> Correction for Bias in Correlations</a>
  <ul class="collapse">
  <li><a href="#defining-the-estimand" id="toc-defining-the-estimand" class="nav-link" data-scroll-target="#defining-the-estimand"><span class="header-section-number">5.5.1</span> Defining the Estimand</a></li>
  <li><a href="#sec-r-corr" id="toc-sec-r-corr" class="nav-link" data-scroll-target="#sec-r-corr"><span class="header-section-number">5.5.2</span> Artifactual Bias and Correction</a></li>
  <li><a href="#correcting-correlations-in-r" id="toc-correcting-correlations-in-r" class="nav-link" data-scroll-target="#correcting-correlations-in-r"><span class="header-section-number">5.5.3</span> Correcting Correlations in R</a></li>
  </ul></li>
  <li><a href="#correction-for-bias-in-standardized-mean-differences-d" id="toc-correction-for-bias-in-standardized-mean-differences-d" class="nav-link" data-scroll-target="#correction-for-bias-in-standardized-mean-differences-d"><span class="header-section-number">5.6</span> Correction for Bias in Standardized Mean Differences (<em>d</em>)</a>
  <ul class="collapse">
  <li><a href="#defining-the-estimand-1" id="toc-defining-the-estimand-1" class="nav-link" data-scroll-target="#defining-the-estimand-1"><span class="header-section-number">5.6.1</span> Defining the Estimand</a></li>
  <li><a href="#sec-d-SMD" id="toc-sec-d-SMD" class="nav-link" data-scroll-target="#sec-d-SMD"><span class="header-section-number">5.6.2</span> Artifact Correction for Unreliability</a></li>
  <li><a href="#correcting-standardized-mean-differences-in-r" id="toc-correcting-standardized-mean-differences-in-r" class="nav-link" data-scroll-target="#correcting-standardized-mean-differences-in-r"><span class="header-section-number">5.6.3</span> Correcting Standardized Mean Differences in R</a></li>
  </ul></li>
  <li><a href="#sec-lim-information" id="toc-sec-lim-information" class="nav-link" data-scroll-target="#sec-lim-information"><span class="header-section-number">5.7</span> Estimating Reliability with Limited Information</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>In general terms, measurement is the process of quantifying an attribute or characteristic of something. In scientific measurement, the measurand is the quantity or the attribute we intend to measure. In the psychological sciences, measurands usually take the form of constructs such as intelligence or anxiety. Often the goal of measurement is to produce quantities (i.e., scores) that accurately reflect the measurand. However, quantities that do not reflect a <em>real</em> attribute can still have useful predictive value (e.g., socio-economic status). It is important to note that measures are not all created equal, some perform better than others. Ideally, measures should produce scores that are consistent and repeatable, this is referred to as the <em>reliability</em> of a measure. A high quality measure should produce highly reliable scores. This section will review what reliability is in theory, how to estimate reliability, and how to correct effect sizes for measurement error.</p>
</section>
<section id="sec-true-score-theory" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-true-score-theory"><span class="header-section-number">5.2</span> Reliability in True Score Theory</h2>
<p>True score theory (or classical test theory) is a mathematical formalization of observed scores obtained from a measurement procedure. Observed scores, <span class="math inline">\(x_{im}\)</span>, is defined as a score obtained from individual <span class="math inline">\(i\)</span> upon measurement <span class="math inline">\(m\)</span>. The true score model assumes that each individual, has a true score, <span class="math inline">\(T_i\)</span>, that stays constant over repeated measurements. Variation in observed scores over repeated measurements is due to measurement-specific error, <span class="math inline">\(e_{im}\)</span>,</p>
<p><span class="math display">\[
x_{im} = T_i+e_{im}.
\]</span></p>
<p>Here, measurements are <em>strictly parallel</em>. Strictly parallel measurements have the following four properties <span class="citation" data-cites="haertel2006">(p.&nbsp;69, <a href="references_page.html#ref-haertel2006" role="doc-biblioref">Haertel 2006</a>)</span>:</p>
<ol type="1">
<li>Measurements have identical specifications. That is, each measurement is obtained with an identical format and procedure.</li>
<li>The distribution of observed scores for each measurement are identical: <span class="math inline">\(f(x_1) = f(x_2) = \ldots\)</span>.</li>
<li>Any set of two measurements are assumed to covary the same as any other set of two measurements: <span class="math inline">\(\sigma_{x_1 x_2} = \sigma_{x_2 x_3} = \sigma_{x_1 x_3} = \ldots\)</span>.</li>
<li>Each measurement equally covaries with any other variable: <span class="math inline">\(\sigma_{x_1 y} = \sigma_{x_2 y} = \ldots\)</span>.</li>
</ol>
<p>True scores can be defined as the expected value (i.e., the mean) of observed scores over repeated measurements such that, <span class="math inline">\(\mathbb{E}_m[x_{im}]=T_{i}\)</span>. Given this assumption, it can be inferred that the average of the resultant errors is zero across repeated measurements, <span class="math inline">\(\mathbb{E}_m[e_{im}]=0\)</span> and therefore the covariance between errors on repeated measurements is zero and the covariance between errors in parallel measurements is zero (<span class="math inline">\(\sigma_{e e'}=0\)</span>). It follows that the covariance between errors and true scores is also zero (<span class="math inline">\(\sigma_{eT}=0\)</span>). The independence between true scores and errors provide convenient parsing of the variance in observed scores (<span class="math inline">\(\sigma^2_{x}\)</span>) into components of variance in true scores (<span class="math inline">\(\sigma_T^2\)</span>) and measurement errors (<span class="math inline">\(\sigma_{e}^2\)</span>),</p>
<p><span id="eq-variance"><span class="math display">\[
\sigma_{x}^2 = \sigma_T^2 + \sigma_{e}^2.
\tag{5.1}\]</span></span></p>
<p>Ultimately we desire to have observed scores that closely resemble true scores, therefore it is important to minimize measurement error variance (<span class="math inline">\(\sigma^2_e\)</span>). If <span class="math inline">\(\sigma_{e}^2 = 0\)</span> then the scores can be said to have perfect reliability, that is, observed scores do not vary upon repeated measurements and thus are identical to true scores. In practice, this is virtually never the case. Since we assume that the covariance between errors in parallel measurements is zero, it becomes apparent that the covariance between observed scores in parallel measurements must solely be attributable to variance in true scores, <span class="math inline">\(\sigma_{xx'}=\,\)</span><span class="math inline">\(\sigma_{TT'} + \sigma_{ee'}=\,\)</span><span class="math inline">\(\sigma_{TT'}=\,\)</span><span class="math inline">\(\sigma_T^2\,\)</span>. In true score theory, reliability can be defined as the proportion of true variance in the total observed variance (<span class="math inline">\(\frac{\sigma_T^2}{\sigma_x^2}\)</span>) or the correlation between observed scores in parallel measurements (<span class="math inline">\(r_{xx'}\)</span>).</p>
<p><span class="math display">\[
r_{xx'}=\frac{\sigma_{xx'}}{\sigma_x\sigma_{x'}}  = \frac{\sigma_T^2}{\sigma^2_{x}}.
\]</span> The reliability is also equivalent to the square of the correlation between observed scores and true scores. To understand why this is the case, note that the covariance between parallel forms of a measure is equivalent to the covariance between observed scores and true scores, <span class="math inline">\(\sigma_{xT}=\)</span><span class="math inline">\(\sigma_{(T+e)T}=\)</span><span class="math inline">\(\sigma^2_T + \sigma_{Te}=\)</span><span class="math inline">\(\sigma^2_T = \sigma_{xx'}\)</span>.</p>
<p><span id="eq-reliability"><span class="math display">\[
r_{xx'} = \frac{\sigma_T^2}{\sigma_{x}^2} = \frac{(\sigma_T^2)^2}{\sigma_x^2 \sigma_T^2}= \frac{\sigma_{xT}^2}{\sigma^2_x\sigma^2_T} = r^2_{xT}.
\tag{5.2}\]</span></span></p>
<p>It is important to emphasize that true scores are expected values over repeated observations and they do not necessarily correspond to an actual, tangible quantity of interest <span class="citation" data-cites="borsboom2002">(<a href="references_page.html#ref-borsboom2002" role="doc-biblioref">Borsboom and Mellenbergh 2002</a>)</span>. As a result, every measurement has a true score, regardless of whether it gauges a concrete attribute or not. For example, if we construct a test by summing the responses to the items: “how many languages can you confidently hold a conversation in?” and “Estimate the number of photos you’ve taken in the last year across all devices”. Even in such nonsensical cases, the test’s composite score retains a true score, but this true score does not mirror a tangible reality.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figure/unreliability_diagram_1.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="figure-caption">Structural diagram illustrating the relationship between true scores, observed scores, and error scores. The pink circle labeled <span class="math inline">\(t\)</span> indicates the true scores, the blue squares labeled with <span class="math inline">\(x\)</span> and <span class="math inline">\(x'\)</span> represent observed scores on parallel measurements, and the red <span class="math inline">\(e\)</span> denotes error. Correlations between <span class="math inline">\(T\)</span>, <span class="math inline">\(x\)</span>, and <span class="math inline">\(x'\)</span> are in terms of reliability (<span class="math inline">\(r_{xx'}\)</span>). Note that <span class="math inline">\(\sqrt{r_{xx'}}=r_{xT}\)</span>.</figcaption>
</figure>
</div>
</section>
<section id="reliability-vs-validity" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="reliability-vs-validity"><span class="header-section-number">5.3</span> Reliability vs Validity</h2>
<p>Reliability and validity are distinct properties in measurement theory. Validity pertains to whether the scores produced by a measure reflects the quantities it is intended to measure <span class="citation" data-cites="kelley1927">(p.&nbsp;14 <a href="references_page.html#ref-kelley1927" role="doc-biblioref">Kelley 1927</a>)</span>. According to <span class="citation" data-cites="borsboom2004">Borsboom, Mellenbergh, and Van Heerden (<a href="references_page.html#ref-borsboom2004" role="doc-biblioref">2004</a>)</span>, a measure is <em>valid</em> if both of the following statements are true:</p>
<ol type="1">
<li><p>The attribute exists.</p></li>
<li><p>Variations in the attribute causally produce variations in the outcomes of the measurement procedure.</p></li>
</ol>
<p>Borsboom’s formulation of validity is simpler and more practical than other formulations such as Cronbach and Meehl’s <span class="citation" data-cites="cronbach1955">(<a href="references_page.html#ref-cronbach1955" role="doc-biblioref">1955</a>)</span> nomological network approach to validity. It is important to note that even if an attribute does not exist (statement 1), scores may still provide predictive utility. For example, socio-economic status (SES) is a formative quantity that is constructed from a composite of education, income, occupation status, etc. Although SES is not causal to these indicators, SES can still be used as a predictor of important life outcomes.</p>
</section>
<section id="estimating-reliability" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="estimating-reliability"><span class="header-section-number">5.4</span> Estimating Reliability</h2>
<p>In practice, reliability must be estimated through indirect methods, this is due to the fact that true scores and errors are unknown. There are many reliability estimators that can be used, however we will go over a selection of internal consistency estimators as well as test-retest stability estimators.</p>
<section id="internal-consistency-estimators" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="internal-consistency-estimators"><span class="header-section-number">5.4.1</span> Internal Consistency Estimators</h3>
<p>Taking multiple measurements and then averaging tends to provide a more stable estimate of true values. For instance, let’s consider the case of Francis <span class="citation" data-cites="galton1907">Galton (<a href="references_page.html#ref-galton1907" role="doc-biblioref">1907</a>)</span>, who conducted a study involving 787 individuals estimating the weight of an ox. On average, each person’s estimate deviated by approximately 37 pounds from the actual weight of the ox, which was recorded as 1198 pounds. However, when all the guesses were averaged together, the combined estimate was 1207 pounds, just a 9 pound difference from the true value. This principle can be extended to broader applications, such as measuring psychological constructs. If we were to assess someone’s level of extraversion using ratings from their mother, father, friend, and sibling, the average of their combined assessments would yield a more reliable score compared to relying solely on a single evaluator. So to create a more stable composite score (<span class="math inline">\(x\)</span>), we can take the score from <span class="math inline">\(\kappa\)</span> items (<span class="math inline">\(\mathbb{x}\)</span>) and sum them such that,</p>
<p><span class="math display">\[
x = \mathbb{x}_1 + \mathbb{x}_2 +...+\mathbb{x}_\kappa
\]</span></p>
<p>The most commonly reported reliability estimator in the psychological sciences is coefficient alpha, also referred to as Cronbach’s alpha. Coefficient alpha, along with other internal consistency estimators, serves the purpose of assessing the reliability of composite scores comprising multiple item scores. Coefficient alpha only requires three parameters to calculate, the number of measurements (<span class="math inline">\(\kappa\)</span>), the variances of each item (<span class="math inline">\(\sigma^2_{\text{i}_m}\)</span>), and the variance of the composite score (<span class="math inline">\(\sigma^2_{x}\)</span>). Coefficient alpha will estimate the reliability of the composite observed score, <span class="math inline">\(x\)</span> (<span class="math inline">\(r_{xx'}\)</span>),</p>
<p><span id="eq-alpha"><span class="math display">\[
_\alpha r_{xx'} = \frac{\kappa}{\kappa-1}\left( 1 - \frac{\sum_{m=1}^\kappa \sigma^2_{\mathbb{x}_m}}{\sigma^2_{x}} \right).
\tag{5.3}\]</span></span></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="unreliability_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figures showing the observed scores upon 10 repeated measurements and the composite observed score for a single person (the true score is denoted with the dashed line). The left panel shows 10 observed scores with a lot of variation (i.e., low reliability). The composite score (dark red dot with error bars), shows wide error bars illustrating the low precision of the observed score score. The right panel also shows 10 observed scores with little variation (i.e., high reliability). The composite score (dark blue dot with error bars), shows narrow error bars illustrating the high precision of the observed score.</figcaption>
</figure>
</div>
</div>
</div>
<p>With tighter assumptions <span class="citation" data-cites="haertel2006">(see <a href="references_page.html#ref-haertel2006" role="doc-biblioref">Haertel 2006</a>)</span>, the formula for coefficient alpha can be simplified to just two parameters: the number of measurements (<span class="math inline">\(\kappa\)</span>) and the average correlation between measured scores (<span class="math inline">\(\bar{r}_{\mathbb{x}_i \mathbb{x}_j}\)</span>, where <span class="math inline">\(i\neq j\)</span>). This formula is known as Spearman-Brown’s prophecy,</p>
<p><span id="eq-sp-brown"><span class="math display">\[
_\text{sb} r_{xx'}= \frac{\kappa \bar{r}_{\mathbb{x}_i \mathbb{x}_j}}{1+(\kappa-1)\bar{r}_{\mathbb{x}_i \mathbb{x}_j}}
\tag{5.4}\]</span></span></p>
<p>This can be simplified further if we have two observed item scores. This formulation is a variation of split-half reliability:</p>
<p><span id="eq-split-half"><span class="math display">\[
_\text{sh}r_{xx'}= \frac{2r_{\mathbb{x}_1 \mathbb{x}_2}}{1+r_{\mathbb{x}_1 \mathbb{x}_2}}
\tag{5.5}\]</span></span></p>
<p>All of these reliability estimators measure internal consistency, therefore they do not account for error outside of the measurement-specific error. There are other sources of error that internal consistency reliability estimates do not account for, such as transient error or rater-specific error.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figure/unreliability_diagram_2.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="figure-caption">Structural model illustrating internal consistency. The pink circle labeled <span class="math inline">\(T\)</span> indicates the true scores, the blue squares, <span class="math inline">\(\mathbb{x}_{1...\kappa}\)</span>, represent the observed scores across multiple measurements, and the red <span class="math inline">\(e\)</span> denotes error. The dark blue hexagon, <span class="math inline">\(x\)</span>, indicates a composite score as a sum of the observed scores (<span class="math inline">\(\mathbb{x}_{1...\kappa}\)</span>). Note that <span class="math inline">\(\sqrt{r_{xx'}}=r_{xT}\)</span>.</figcaption>
</figure>
</div>
</section>
<section id="calculating-internal-consistency-in-r" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="calculating-internal-consistency-in-r"><span class="header-section-number">5.4.2</span> Calculating Internal Consistency in R</h3>
<p>Let us simulate a data set of 50 individuals that were measured four times resulting in four sets of scores (<code>x1,x2,x3,x4</code>) that have the same true score and error variance. Then let us calculate a composite score (<code>x</code>) from these sub-scores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set seed</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">343</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set sample size</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>T_score <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># simulate true scores</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># simulate observed scores for measurement 1</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># simulate observed scores for measurement 2</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># simulate observed scores for measurement 3</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>) <span class="co"># simulate observed scores for measurement 4</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate composite score</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> x4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let us calculate coefficient alpha from the formula provided in <a href="#eq-alpha">Equation&nbsp;<span>5.3</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1. calculate variance of observed (measured) scores</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>var_xm <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">var</span>(x1),<span class="fu">var</span>(x2),<span class="fu">var</span>(x3),<span class="fu">var</span>(x4))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2. get number of items (k)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(var_xm)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3. calculate variance of composite score</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>var_x <span class="ot">&lt;-</span> <span class="fu">var</span>(x)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># step 4. calculate coefficient alpha reliability</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>rxx_alpha <span class="ot">&lt;-</span> k <span class="sc">/</span> (k<span class="dv">-1</span>) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(var_xm)<span class="sc">/</span>(var_x))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># display reliability</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx_alpha,<span class="dv">3</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.775</code></pre>
</div>
</div>
<p>With the simplification of Coefficient alpha’s formula, let us calculate the reliability via Spearman-Brown’s prophecy formula provided in <a href="#eq-sp-brown">Equation&nbsp;<span>5.4</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1. get correlation matrix between all observed scores</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>corr_mat <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="fu">cbind</span>(x1,x2,x3,x4))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2. average off-diagonal elements of matrix</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(corr_mat) <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>rxixj <span class="ot">&lt;-</span> <span class="fu">mean</span>(corr_mat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3. get number of items (k)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">dim</span>(corr_mat)[<span class="dv">1</span>]</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># step 4. calculate Spearman-Brown reliability</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>rxx_SB <span class="ot">&lt;-</span> k <span class="sc">*</span> rxixj <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> (k<span class="dv">-1</span>) <span class="sc">*</span> rxixj)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># display reliability</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx_SB,<span class="dv">3</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.775</code></pre>
</div>
</div>
<p>If we simplify even further, we can calculate the Split-Half reliability formula provided in <a href="#eq-split-half">Equation&nbsp;<span>5.5</span></a>,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1. make composite scores for each half of the observed scores</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>xh1 <span class="ot">&lt;-</span> (x1 <span class="sc">+</span> x2)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>xh2 <span class="ot">&lt;-</span> (x3 <span class="sc">+</span> x4)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2. calculate the correlation between the scores of both halves</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>rx1x2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(xh1,xh2)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3. calculate the split-half reliability</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>rxx_SH <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>rx1x2 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> rx1x2)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># display reliability</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx_SH,<span class="dv">3</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.824</code></pre>
</div>
</div>
<p>Lets see how the results compare to the actual reliability,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate true reliability, true scores must be re-scaled by number of items</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>rxx <span class="ot">=</span> <span class="fu">var</span>(k<span class="sc">*</span>T_score) <span class="sc">/</span> var_x</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># display actual reliability</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx,<span class="dv">3</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.734</code></pre>
</div>
</div>
<p>In this case, the reliability estimates do a fairly good job of estimating the true reliability of the observed scores. We can also use the <code>alpha</code> function from the <code>psych</code> package <span class="citation" data-cites="psych:p2017">(<a href="references_page.html#ref-psych:p2017" role="doc-biblioref"><span>“Psych: Procedures for Personality and Psychological Research”</span> 2017</a>)</span> to estimate coefficient alpha too. It also provides additional item level information that is quite useful:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load in package</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('psych')</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute summary reliability (only need first table)</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">alpha</span>(<span class="fu">cbind</span>(x1,x2,x3,x4))[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha   G6(smc) average_r      S/N        ase        mean
 0.7749847 0.7751377 0.7337024 0.4628829 3.447166 0.05141467 -0.04386823
        sd  median_r
 0.9567892 0.4571798</code></pre>
</div>
</div>
</section>
<section id="test-retest-stability-estimator" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="test-retest-stability-estimator"><span class="header-section-number">5.4.3</span> Test-Retest Stability Estimator</h3>
<p>Transient errors represent fluctuations in observed scores over time. These fluctuations, even if they are systematic (e.g., fatigue over the course of a single day), add extraneous within-person variance that can mask true scores. Considering transient fluctuations as error depends on the research goal, so it is important for researchers to take care in considering which variance components should be considered error in their study (see <a href="#sec-sources"><span>Section&nbsp;5.4.5</span></a>). To estimate test-retest reliability, we can compute the correlation between the measurement at time 1 (<span class="math inline">\(x_{t_1}\)</span>) and the second measurement at time 2 (<span class="math inline">\(x_{t_2}\)</span>),</p>
<p><span class="math display">\[
_\text{tr}r_{xx'}= r_{x_{t_1}x_{t_2}}.
\]</span></p>
<p>Note that calculating the pearson correlation coefficient between time-points ignores systematic changes (e.g., practice effects).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="unreliability_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Illustrating test-retest reliability. Top-left and top-right panels show the correlation between observed scores at both time-points for a measure that has low and high reliability, respectively. Bottom-left and bottom-right panels show the within-person change from time-point 1 to time-point 2 for scores with low and high reliability, respectively.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="calculating-test-retest-reliability-in-r" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="calculating-test-retest-reliability-in-r"><span class="header-section-number">5.4.4</span> Calculating Test-Retest Reliability in R</h3>
<p>Lets calculate test-retest reliability in R. First, we can simulate observed scores at two time points, <code>xTime1</code> and <code>xTime2</code>. We can assume that the true scores remain constant between time points. Second, we can calculate the correlation between the observed scores at each time point (<code>rxx</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set sample size</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate true scores</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>T_score <span class="ot">=</span> <span class="fu">rnorm</span>(n,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate scores at time 1</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>xTime1 <span class="ot">=</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n,<span class="dv">0</span>,.<span class="dv">5</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate scores at time 2</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>xTime2 <span class="ot">=</span> T_score <span class="sc">+</span> <span class="fu">rnorm</span>(n,<span class="dv">0</span>,.<span class="dv">5</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate test-retest reliability</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>rxx <span class="ot">=</span> <span class="fu">cor</span>(xTime1,xTime2)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co"># display reliability</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.755</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare with true reliability</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>rxx_true <span class="ot">=</span> <span class="fu">var</span>(T_score) <span class="sc">/</span> <span class="fu">var</span>(xTime1)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># display actual reliability</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(rxx_true,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.779</code></pre>
</div>
</div>
</section>
<section id="sec-sources" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="sec-sources"><span class="header-section-number">5.4.5</span> Sources of Measurement Error</h3>
<p>Measurement error variance can itself be broken down into multiple sources of error (e.g., transient, ). Depending on the study, different sources of error may be more relevant than others. It is important for a researcher to choose the right reliability estimator for their study since they account for different sources of measurement error. A description of four of the most common sources of error is adapted from table 1 of <span class="citation" data-cites="wiernik2020">Wiernik and Dahlke (<a href="references_page.html#ref-wiernik2020" role="doc-biblioref">2020</a>)</span>:</p>
<ol type="1">
<li><p>Random Response Error: Genuine randomness in responses. Examples include: motor errors and variation in response time.</p></li>
<li><p>Time/Environment-Specific (Transient) Error: Fluctuations in scores as a result of the specific time or environment of the measurement. For instance, if researchers administered an ability test to a sample of undergraduate students throughout the course of a day, the student’s who complete the test at the end of the day will likely perform worse than participant’s who completed due to fatigue rather than ability. Errors due to illness, mood, hunger, environmental distractors, etc. all fall under the umbrella of transient errors.</p></li>
<li><p>Instrument-Specific Error: Error due to the specific content or make-up of the measurement instrument. For example, a psychological scale using Likert items may show participant’s idiosyncratic interpretations of questions and response options rather than their standing on the latent construct.</p></li>
<li><p>Rater/Observer-Specific Error: Errors induced by idiosyncratic biases of individual raters and rater by ratee interactions (e.g., Teacher A gives higher grades to students who stay after class).</p></li>
</ol>
<p>Different estimators of reliability account for different sources of measurement error therefore depending on the research design, it is important to carefully choose which reliability is most relevant for your use case. Note that even if two estimators account for the same types of measurement error, they likely hold different assumptions that may be violated in a given research context.</p>
<table class="table">
<caption>List of reliability coefficients and the sources of error they account for. The sources of error are denoted by the columns labeled 1-4, corresponding to each of the four sources of error.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Estimator</th>
<th>Description</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Coefficient Alpha</td>
<td>Internal consistency coefficient for composite measures.</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Coefficient Omega</td>
<td>Internal consistency coefficient for composite measures with specified factor structure.</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Split-Half</td>
<td>Internal consistency coefficient for measurements that are split into two halves.</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Kuder-Richardson 20</td>
<td>Internal consistency when observed scores are binary (special case of coefficient alpha).</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Item Response Theory Reliability</td>
<td>Reliability coefficient derived from item response theory (as opposed to classical test theory)</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Inter-Rater/Inter-Observer Reliability</td>
<td>Consistency in scoring between raters/observers.</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">X️</td>
</tr>
<tr class="odd">
<td>Test-Retest</td>
<td>Stability coefficient for repeated measurements across time</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td>Delayed Coefficient Alpha</td>
<td>Average of all possible split-half reliabilities</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>G-Coefficient</td>
<td>Reliability coefficient derived from generalizability theory (G-theory). Can incorporate any source of error if enough data is present.</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
<td style="text-align: center;">X️</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="correction-for-bias-in-correlations" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="correction-for-bias-in-correlations"><span class="header-section-number">5.5</span> Correction for Bias in Correlations</h2>
<section id="defining-the-estimand" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="defining-the-estimand"><span class="header-section-number">5.5.1</span> Defining the Estimand</h3>
<p>Continuing with our emphasis on clearly defining our quantity of interest (i.e., the estimand) prior to applying any corrections, let us define it. Our estimand here is the population correlation between true scores of our independent and dependent variables. We can define the observed scores of the independent and dependent variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> as,</p>
<p><span class="math display">\[
x=T+e_x
\]</span></p>
<p><span class="math display">\[
y=U+e_y.
\]</span></p>
<p>Where <span class="math inline">\(T\)</span> and <span class="math inline">\(U\)</span> are the true scores for the independent and dependent variables, respectively. The true score correlation can thus be be denoted by, <span class="math inline">\(\rho_{TU}\)</span>, and can be defined as the standardized covariance,</p>
<p><span class="math display">\[
\rho_{TU} = \frac{\sigma_{TU}}{\sigma_{T}\sigma_{U}}.
\]</span></p>
<p>In a given study, we will only have knowledge of the observed scores of the independent and dependent variables, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, therefore the observed study correlation is <span class="math inline">\(r_{xy}\)</span>. The relationship between the observed correlation and the true population correlation is,</p>
<p><span class="math display">\[
r_{xy} = a\rho_{TU} + \varepsilon.
\]</span></p>
<p>Where <span class="math inline">\(a\)</span> is the biasing factor. An unbiased estimate of the true score population correlation (<span class="math inline">\(\rho_{TU}\)</span>) can then be calculated by dividing the obsereved study correlation by the biasing factor,</p>
<p><span class="math display">\[
r_c = \frac{r_{xy}}{a}.
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figure/diagram-estimand-reliability-r.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">This figure shows the relationship between the true scores, observed scores, and error scores. The true score correlation is denoted by the curved arrow connecting the circles indicating true score variables, <em>T</em> and <em>U</em>.</figcaption>
</figure>
</div>
</section>
<section id="sec-r-corr" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="sec-r-corr"><span class="header-section-number">5.5.2</span> Artifactual Bias and Correction</h3>
<p>Measurement error induces systematic bias in effect size estimates such as correlation coefficients <span class="citation" data-cites="hunter1990a">Spearman (<a href="references_page.html#ref-spearman1904" role="doc-biblioref">1904</a>)</span>. In the population, let us assume there is some factor <span class="math inline">\(a\)</span> that accounts for the systematic bias in observed score correlations (<span class="math inline">\(\rho_{xy}\)</span>) relative to true score correlations (<span class="math inline">\(\rho_{TU}\)</span>), such that</p>
<p><span class="math display">\[
\rho_{xy} = a \rho_{TU}.
\]</span></p>
<p>Since the correlation is defined as the covariance standardized by the standard deviations, the population correlation between true scores, <span class="math inline">\(T\)</span> and <span class="math inline">\(U\)</span>, is defined as,</p>
<p><span class="math display">\[
\rho_{TU}=\frac{\sigma_{TU}}{\sigma_{T} \sigma_{U}}.
\]</span></p>
<p>Likewise the correlation between the observed scores, <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, would be the observed covariance divided by the observed standard deviations. <span class="math display">\[
\rho_{xy} =\frac{\sigma_{xy}}{\sigma_{x} \sigma_{y}}.
\]</span> However, if we assume that there is no covariance between errors in <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> (<span class="math inline">\(\sigma_{e_x e_y} = 0\)</span>), then the covariance between observed scores is only attributable to the covariance between true scores, therefore <span class="math inline">\(\sigma_{xy} = \sigma_{TU}\)</span>. This means that the observed score correlation can be expressed as,</p>
<p><span id="eq-bias"><span class="math display">\[
\rho_{xy} =\frac{\sigma_{TU}}{\sigma_{x} \sigma_{y}}.
\tag{5.6}\]</span></span></p>
<p>Now the only difference between the observed score correlation and the true score correlation is the standard deviations in the denominator. In the presence of measurement error, the observed score standard deviations (<span class="math inline">\(\sigma_x\)</span> and <span class="math inline">\(\sigma_y\)</span>) will be larger than the true score standard deviations (<span class="math inline">\(\sigma_{T}\)</span> and <span class="math inline">\(\sigma_{U}\)</span>). Using the definition of reliability, we can show how the observed variance is inflated compared to the true variance as a function of reliability. Since the reliability is defined as the ratio of true variance to total observed variance (see <a href="#eq-reliability">Equation&nbsp;<span>5.2</span></a>), we can see how reliability inflates the observed variance</p>
<span class="math display">\[\begin{align}
\sigma^2_x &amp;=\sigma^2_{T} \left(\frac{\sigma^2_{x}}{\sigma^2_{T}} \right)
\\ &amp;= \sigma^2_{T}\left(\frac{1}{r_{xx'}} \right)
\\ &amp;= \frac{\sigma^2_{T}}{r_{xx'}}.
\end{align}\]</span>
<p>Therefore the observed standard deviation is,</p>
<p><span id="eq-sd-me"><span class="math display">\[
\sigma_x = \frac{\sigma_{T}}{\sqrt{r_{xx'}}}.
\tag{5.7}\]</span></span></p>
<p>If we use the definition of an observed score correlation (<a href="#eq-bias">Equation&nbsp;<span>5.6</span></a>), then we can replace <span class="math inline">\(\sigma_x\)</span> and <span class="math inline">\(\sigma_y\)</span> with <span class="math inline">\(\frac{\sigma_{T}}{\sqrt{r_{xx'}}}\)</span> and <span class="math inline">\(\frac{\sigma_{U}}{\sqrt{r_{yy'}}}\)</span>, respectively. Now we can see how the observed score correlation differs from the true score correlation:</p>
<span class="math display">\[\begin{align}
\rho_{xy} &amp;= \frac{\sigma_{T U}}{\left[\frac{\sigma_{T}}{\sqrt{r_{xx'}}} \right] \left[ \frac{\sigma_{U}}{\sqrt{r_{yy'}}} \right] }
\\ &amp;= \frac{\sigma_{T U}}{\sigma_{T}\sigma_{U}} \cdot \sqrt{r_{yy'}}\sqrt{r_{xx'}}
\\ &amp;= \rho_{TU} \sqrt{r_{yy'}}\sqrt{r_{xx'}}
\end{align}\]</span>
<p>This attenuation formula was first derived by <span class="citation" data-cites="spearman1904">Spearman (<a href="references_page.html#ref-spearman1904" role="doc-biblioref">1904</a>)</span>. Note that this formulation requires that there is no correlation between <span class="math inline">\(e_x\)</span> and <span class="math inline">\(e_y\)</span> (<span class="math inline">\(r_{e_xe_y}=0\)</span>). The study observed correlation will also contain sampling error and thus can be expressed by, <span class="math display">\[
r_{xy} = \rho_{xy} + \varepsilon_o
\]</span> We can also express it in terms of our estimand, the population true score correlation (<span class="math inline">\(\rho_{TU}\)</span>),</p>
<p><span class="math display">\[
r_{xy} = \rho_{TU}\sqrt{r_{xx'}r_{xx'}} + \varepsilon_o.
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="unreliability_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Visualizing the attenuation of observed correlation (<span class="math inline">\(\rho_{xy}\)</span>) due to measurement error. The left panel shows a situation where only one variable (<span class="math inline">\(x\)</span>) has measurement error. The observed correlation increases as a function of the true correlation <span class="math inline">\(\rho_{TU}\)</span> (darker lines indicate a higher true score correlation) and the reliability of <span class="math inline">\(x\)</span> (x-axis). The right panel shows the attenuation of the correlation when both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> variables are affected by measurement error. The darker end of the gradient shows a higher correlation, while the lighter end represents a smaller correlation (the true score correlation sits on the top where no measurement error is present, <span class="math inline">\(r_{xx'}=r_{yy'}=1\)</span>).</figcaption>
</figure>
</div>
</div>
</div>
<p>It becomes apparent that if we have the reliability of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, we can obtain an unbiased estimate of <span class="math inline">\(\rho_{TU}\)</span> by dividing both sides of the above equation by <span class="math inline">\(\sqrt{r_{xx'}r_{xx'}}\)</span> such that,</p>
<p><span class="math display">\[
\frac{r_{xy}}{\sqrt{r_{xx'}r_{xx'}}} =\rho_{TU} + \frac{\varepsilon_o}{\sqrt{r_{xx'}r_{xx'}}}.
\]</span></p>
<p>Therefore the corrected study correlation, <span class="math inline">\(r_c\)</span>, is defined as,</p>
<p><span class="math display">\[
r_c = \frac{r_{xy}}{\sqrt{r_{xx'}r_{xx'}}}.
\]</span></p>
<p>The sampling error of the corrected study correlation is,</p>
<p><span class="math display">\[
\varepsilon_c = \frac{\varepsilon_{o}}{\sqrt{r_{xx'}r_{xx'}}}
\]</span></p>
<p>and thus the sampling variance would be,</p>
<p><span class="math display">\[
\sigma^2_{\varepsilon_c} = \frac{\sigma^2_{\varepsilon_{o}}}{r_{xx'}r_{xx'}}.
\]</span></p>
</section>
<section id="correcting-correlations-in-r" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="correcting-correlations-in-r"><span class="header-section-number">5.5.3</span> Correcting Correlations in R</h3>
<p>We can simulate continuous data that contains measurement error by using the <code>simulate_r_sample</code> function in the <code>psychmeta</code> package. Below we will simulate observed scores (<code>x_score</code> and <code>y_score</code>) and true scores (<code>T_score</code> and <code>U_score</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('psychmeta')</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psychmeta)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># define parameters</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>rhoTU <span class="ot">&lt;-</span> .<span class="dv">5</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>rxx <span class="ot">&lt;-</span> .<span class="dv">8</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ryy <span class="ot">&lt;-</span> .<span class="dv">7</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">simulate_r_sample</span>(<span class="at">n =</span> n, </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>                          <span class="at">rho_mat =</span> <span class="fu">reshape_vec2mat</span>(rhoTU),</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>                          <span class="at">rel_vec =</span> <span class="fu">c</span>(rxx, ryy), </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sr_vec =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">var_names =</span> <span class="fu">c</span>(<span class="st">"x"</span>,<span class="st">"y"</span>))</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain observed scrores</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>x_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>observed<span class="sc">$</span>x</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>y_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>observed<span class="sc">$</span>y</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain true scores</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>T_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>true<span class="sc">$</span>x</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>U_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>true<span class="sc">$</span>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we can compute observed score (<code>rxy</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute observed score correlation and standard error</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>rxy <span class="ot">&lt;-</span> <span class="fu">cor</span>(x_score,y_score)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># compute sampling variance of observed score correlation</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>var_e_o <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>rxy<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n<span class="dv">-2</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'rxy = '</span>,<span class="fu">round</span>(rxy,<span class="dv">3</span>),<span class="st">'  var_e_o = '</span>,<span class="fu">round</span>(var_e_o,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rxy = 0.351  var_e_o = 0.0018"</code></pre>
</div>
</div>
<p>Let us now compare the observed correlation with the true score correlation (<code>rTU</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute observed score correlation and standard error</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rTU <span class="ot">&lt;-</span> <span class="fu">cor</span>(T_score,U_score)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># compute sampling variance of observed score correlation</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>var_e <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span>rTU<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n<span class="dv">-2</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'rTU = '</span>,<span class="fu">round</span>(rTU,<span class="dv">3</span>),<span class="st">'  var_e = '</span>,<span class="fu">round</span>(var_e,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rTU = 0.463  var_e = 0.0016"</code></pre>
</div>
</div>
<p>The observed correlation is substantially lower than the true score correlation. In order to correct the observed score correlation, we can calculate it by hand or use the <code>correct_r()</code> function. Lets first correct by hand using the equations in <a href="#sec-r-corr"><span>Section&nbsp;5.5.2</span></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correct correlation coefficient</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rc <span class="ot">&lt;-</span> rxy <span class="sc">/</span> <span class="fu">sqrt</span>(rxx<span class="sc">*</span>ryy)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># correct sampling variance</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>var_e_c <span class="ot">&lt;-</span> var_e_o <span class="sc">/</span> <span class="fu">sqrt</span>(rxx<span class="sc">*</span>ryy)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="fu">paste0</span>(<span class="st">'rc = '</span>,<span class="fu">round</span>(rc,<span class="dv">3</span>)),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste0</span>(<span class="st">'var_e_c = '</span>,<span class="fu">round</span>(var_e_c,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]              
[1,] "rc = 0.47"       
[2,] "var_e_c = 0.0024"</code></pre>
</div>
</div>
<p>Now lets correct the correlation with the <code>correct_r()</code> function,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correct correlation</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">correct_r</span>(<span class="at">rxyi =</span> rxy,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">rxx =</span> rxx,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">ryy =</span> ryy,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlations Corrected for Measurement Error:
---------------------------------------------------------------------------------------
  value CI_LL_95 CI_UL_95   n n_effective
1  0.47    0.364    0.569 500         222</code></pre>
</div>
</div>
<p>As we can see, the corrected correlation (<span class="math inline">\(r_c = .470\)</span>) is a more accurate estimate of the true score population correlation <span class="math inline">\(\rho_{TU} = .500\)</span>, than the observed score correlation (<span class="math inline">\(r_{xy}=.351\)</span>).</p>
</section>
</section>
<section id="correction-for-bias-in-standardized-mean-differences-d" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="correction-for-bias-in-standardized-mean-differences-d"><span class="header-section-number">5.6</span> Correction for Bias in Standardized Mean Differences (<em>d</em>)</h2>
<section id="defining-the-estimand-1" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="defining-the-estimand-1"><span class="header-section-number">5.6.1</span> Defining the Estimand</h3>
<p>Prior to correcting for measurement error let us define our estimand. Our estimand here is the difference in the means of group <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> with respect to the true scores of our dependent variable. We can define the observed scores of the independent and dependent variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> as,</p>
<p><span class="math display">\[
y_A = U_A + e_A
\]</span></p>
<p><span class="math display">\[
y_B = U_B + e_B.
\]</span></p>
<p>Where <span class="math inline">\(U_A\)</span> and <span class="math inline">\(U_B\)</span> are the true scores for group <span class="math inline">\(A\)</span> and group <span class="math inline">\(B\)</span>, respectively. The true score standardized mean difference can thus be be denoted by, <span class="math inline">\(\delta_{U}\)</span>, and can be defined as,</p>
<p><span class="math display">\[
\delta_{U} = \frac{\overline{U}_A - \overline{U}_B}{\sigma_{U_P}}.
\]</span></p>
<p>Where <span class="math inline">\(\overline{U}\)</span> is the mean of true scores for the respective group. In a given study, we only have access to the observed scores of the dependent variables, <span class="math inline">\(y\)</span>, therefore the observed score study standardized mean difference is <span class="math inline">\(d_{y}\)</span>. The relationship between the population true score standardized mean difference (<span class="math inline">\(\delta_U\)</span>) can be related to the observed study standardized mean difference with the following formulation:</p>
<p><span class="math display">\[
d_y = a\delta_U+\varepsilon.
\]</span></p>
<p>Where <span class="math inline">\(a\)</span> is the artifactual bias induced by measurement error and <span class="math inline">\(\varepsilon\)</span> denotes sampling error. To obtain an unbiased estimate of <span class="math inline">\(\delta_{U}\)</span>, we can correct the observed standardized mean difference by dividing by <span class="math inline">\(a\)</span>,</p>
<p><span class="math display">\[
d_c = \frac{d_y}{a}.
\]</span></p>
</section>
<section id="sec-d-SMD" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="sec-d-SMD"><span class="header-section-number">5.6.2</span> Artifact Correction for Unreliability</h3>
<p>We can calculate the standardized mean difference of the observed scores by dividing the mean difference in observed scores (<span class="math inline">\(\bar{y}_A-\bar{y}_B\)</span>) by the pooled standard deviation (<span class="math inline">\(\sigma_p\)</span>). It is important to note that the mean of true scores and the mean of observed scores will be identical due to the fact that measurement error only affects variance in scores rather than the means. Therefore, we can express the observed standardized mean difference as,</p>
<p><span class="math display">\[
d_y = \frac{\bar{y}_A-\bar{y}_B}{\sigma_{y_P}} = \frac{\overline{U}_A-\overline{U}_B}{\sigma_{y_P}}.
\]</span></p>
<p>The pooled standard deviation is a weighted average of the observed score standard deviations,</p>
<p><span class="math display">\[
\sigma_{y_P}=\sqrt{\frac{(n_A+1)\sigma^2_{y_A}+(n_B+1)\sigma^2_{y_B}}{n_A+n_B-2}}.
\]</span></p>
<p>To express <span class="math inline">\(\sigma_{y_P}\)</span> in terms of the true score standard deviations, we can replace the observed score standard deviations with the attenuated true score standard deviation in <a href="#eq-sd-me">Equation&nbsp;<span>5.7</span></a>,</p>
<p><span class="math display">\[
\sigma_{y_P} = \sqrt{\frac{(n_A+1)\left(\frac{\sigma^2_{U_A}}{r_{yy'_A}}\right)+(n_B+1)\left(\frac{\sigma^2_{U_B}}{r_{yy'_B}}\right)}{n_A + n_B - 2}}.
\]</span></p>
<p>Alternatively, we can pool the reliability and the true score standard deviations separately so that we can obtain a simplified version of the above equation,</p>
<p><span class="math display">\[
\sigma_{U_P} = \sqrt{\frac{(n_A+1)\sigma_{U_A}^2+(n_B+1)\sigma_{U_B}^2}{n_A + n_B - 2}}
\]</span></p>
<p><span class="math display">\[
r_{yy'_P} = \sqrt{\frac{(n_A+1) r_{yy'_A}^2+(n_B+1)r_{yy'_B}^2}{n_A + n_B - 2}}.
\]</span></p>
<p>Then we can express <span class="math inline">\(\sigma_{y_P}\)</span> similarly to <a href="#eq-sd-me">Equation&nbsp;<span>5.7</span></a>,</p>
<p><span class="math display">\[
\sigma_{y_P} = \frac{\sigma_{U_P}}{\sqrt{r_{yy'_P}}}
\]</span></p>
<p>Now we can put it all together and see how the observed score standardized mean difference (<span class="math inline">\(\delta_y\)</span>) is biased relative to the true score standardized mean difference (<span class="math inline">\(\delta_U\)</span>),</p>
<span class="math display">\[\begin{align}
\delta_y &amp;= \frac{\bar{y}_A-\bar{y}_B}{\sigma_{y_P}}
\\[1em] &amp;= \frac{\overline{U}_A-\overline{U}_B}{\sigma_{y_P}}
\\[1em] &amp;= \frac{\overline{U}_A-\overline{U}_B}{\frac{\sigma_{U_P}}{\sqrt{r_{yy'_P}}}}
\\[1em] &amp;= \frac{\overline{U}_A-\overline{U}_B}{\sigma_{U_P}}\sqrt{r_{yy'_P}}
\\[1em] &amp;= \delta_U\sqrt{r_{yy'_P}}.
\end{align}\]</span>
<p>This attenuation bias is very similar to the one we saw in the correlation, with the only difference being that the pooled reliability is used here instead of the total sample reliability. Within a study, the observed study standardized mean difference (<span class="math inline">\(d_y\)</span>) is a function of the observed population standardized mean (<span class="math inline">\(\delta_y\)</span>), artifact bias (<span class="math inline">\(a\)</span>), and sampling error (<span class="math inline">\(\varepsilon\)</span>),</p>
<p><span class="math display">\[
d_y = \delta_y + \varepsilon_o.
\]</span></p>
<p>replacing the observed population standardized mean difference, <span class="math inline">\(\delta_y\)</span>, with <span class="math inline">\(\delta_U\sqrt{r_{yy'_P}}\)</span>, gives us,</p>
<p><span class="math display">\[
d_y = \delta_U\sqrt{r_{yy'_P}} + \varepsilon.
\]</span> Therefore to obtain the corrected study standardized mean difference (<span class="math inline">\(d_c\)</span>) we can divide <span class="math inline">\(d_y\)</span> by the attenuation factor,</p>
<p><span class="math display">\[
d_c = \frac{d_y}{\sqrt{r_{yy'_P}}}.
\]</span></p>
<p>Where the sampling variance of the corrected SMD must also be similarly adjusted,</p>
<p><span class="math display">\[
\sigma^2_{\varepsilon_c} = \frac{\sigma^2_{\varepsilon_o}}{r_{yy'_P}}.
\]</span></p>
<p>Although the attenuation factor is quite simple, in more complex formulations (e.g., bivariate direct range restriction), it will be easier to apply a simplified correction for the sampling variance using the corrected correlation coefficient:</p>
<p><span class="math display">\[
\sigma^2_{\varepsilon_c} = \sigma^2_{\varepsilon_o}\left(\frac{d_c}{d_y}\right)^2.
\]</span> It is important to point out that this correction can only be done if when estimates of the within-group reliability are available. It is common that studies will only report the full sample reliability. If there are differences between groups on the variable, the total sample reliability will over-estimate the within-group reliability. When the total sample reliability is all that is available, to correct <span class="math inline">\(d_y\)</span>, we must first convert it to a point-biserial correlation coefficient (<span class="math inline">\(r_o\)</span>) using the observed proportion of subjects in either group <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> (<span class="math inline">\(p\,\)</span>; it does not matter which one is chosen, as long as it is consistent throughout).</p>
<p><span class="math display">\[
r_o = \frac{d_y}{\sqrt{\frac{1}{p(1-p)}+d_y^2}}.
\]</span></p>
<p>Then correct <span class="math inline">\(r_o\)</span> for the total sample reliability,</p>
<p><span class="math display">\[
r_c = \frac{r_o}{\sqrt{r_{yy'}}}
\]</span></p>
<p>Then we can convert <span class="math inline">\(r_c\)</span> back into <span class="math inline">\(d_c\)</span>,</p>
<p><span class="math display">\[
d_c = \frac{r_c}{\sqrt{p(1-p)(1-r_c^2)}}
\]</span></p>
<p>The same process can be done for the sampling variance as well, but instead we can put it all into one equation,</p>
<p><span class="math display">\[
\sigma^2_{\varepsilon_c} = \frac {\sigma^2_{\varepsilon_o}\left(\frac{r_c}{r_o}\right)^2} {\left(1+d_y^2p[1-p]\right)^3\left(1-r_c^2\right)^3}
\]</span></p>
</section>
<section id="correcting-standardized-mean-differences-in-r" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="correcting-standardized-mean-differences-in-r"><span class="header-section-number">5.6.3</span> Correcting Standardized Mean Differences in R</h3>
<p>We can simulate data that contains measurement error by using the <code>simulate_d_sample</code> function in the <code>psychmeta</code> package. Below we will simulate observed scores (<code>y_score</code>) and true scores (<code>U_score</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('psychmeta')</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psychmeta)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># define parameters</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>Means <span class="ot">=</span> <span class="fu">c</span>()</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>ryyA <span class="ot">&lt;-</span> .<span class="dv">75</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>ryyB <span class="ot">&lt;-</span> .<span class="dv">70</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>nA <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>nB <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> nA <span class="sc">+</span> nB</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">simulate_d_sample</span>(<span class="at">n_vec =</span> <span class="fu">c</span>(nA, nB), </span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>                         <span class="at">rho_mat_list =</span> <span class="fu">list</span>(<span class="fu">reshape_vec2mat</span>(<span class="dv">1</span>),<span class="fu">reshape_vec2mat</span>(<span class="dv">1</span>)),</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mu_mat =</span> <span class="fu">rbind</span>(<span class="fu">c</span>(.<span class="dv">5</span>,<span class="dv">0</span>),</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>                                        <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)), </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sigma_mat =</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>                                           <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)),</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>                         <span class="at">rel_mat =</span> <span class="fu">rbind</span>(<span class="fu">c</span>(ryyA,<span class="dv">1</span>),</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">c</span>(ryyB,<span class="dv">1</span>)), </span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sr_vec =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>                         <span class="at">group_names =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>))</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain observed scores</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>y_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>observed<span class="sc">$</span>y1</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>group <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>observed<span class="sc">$</span>group</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain true scores</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>U_score <span class="ot">&lt;-</span> data<span class="sc">$</span>data<span class="sc">$</span>true<span class="sc">$</span>y1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we can compute observed score standardized mean difference (<code>dy</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute observed score means and standard deviations</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>Mean_A <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_score[group<span class="sc">==</span><span class="st">'A'</span>])</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>Mean_B <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_score[group<span class="sc">==</span><span class="st">'B'</span>])</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>SD_A <span class="ot">&lt;-</span> <span class="fu">sd</span>(y_score[group<span class="sc">==</span><span class="st">'A'</span>])</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>SD_B <span class="ot">&lt;-</span> <span class="fu">sd</span>(y_score[group<span class="sc">==</span><span class="st">'B'</span>])</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># compute pooled standard deviation</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>SD_P <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( ((nA<span class="dv">-1</span>)<span class="sc">*</span>SD_A<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (nB<span class="dv">-1</span>)<span class="sc">*</span>SD_B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (nA<span class="sc">+</span>nB<span class="dv">-2</span>) )</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># compute standardized mean difference</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>dy <span class="ot">&lt;-</span> (Mean_A <span class="sc">-</span> Mean_B) <span class="sc">/</span> SD_P</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co"># compute sampling variance of observed score correlation</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>var_e_o <span class="ot">&lt;-</span> n<span class="sc">/</span>(nA<span class="sc">*</span>nB) <span class="sc">+</span> dy<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span>n)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'dy = '</span>,<span class="fu">round</span>(dy,<span class="dv">3</span>),<span class="st">'  var_e_o = '</span>,<span class="fu">round</span>(var_e_o,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "dy = 0.273  var_e_o = 0.0202"</code></pre>
</div>
</div>
<p>Let us now compare the observed score standardized mean difference with the true score standardized mean difference (<code>dU</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute true score means and standard deviations</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>Mean_A <span class="ot">&lt;-</span> <span class="fu">mean</span>(U_score[group<span class="sc">==</span><span class="st">'A'</span>])</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Mean_B <span class="ot">&lt;-</span> <span class="fu">mean</span>(U_score[group<span class="sc">==</span><span class="st">'B'</span>])</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>SD_A <span class="ot">&lt;-</span> <span class="fu">sd</span>(U_score[group<span class="sc">==</span><span class="st">'A'</span>])</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>SD_B <span class="ot">&lt;-</span> <span class="fu">sd</span>(U_score[group<span class="sc">==</span><span class="st">'B'</span>])</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># compute pooled standard deviation</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>SD_P <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( ((nA<span class="dv">-1</span>)<span class="sc">*</span>SD_A<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (nB<span class="dv">-1</span>)<span class="sc">*</span>SD_B<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (nA<span class="sc">+</span>nB<span class="dv">-2</span>) )</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># compute standardized mean difference</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>dU <span class="ot">&lt;-</span> (Mean_A <span class="sc">-</span> Mean_B) <span class="sc">/</span> SD_P</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="co"># compute sampling variance of the true score SMD</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>var_e <span class="ot">&lt;-</span> n<span class="sc">/</span>(nA<span class="sc">*</span>nB) <span class="sc">+</span> dy<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span>n)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'dU = '</span>,<span class="fu">round</span>(dU,<span class="dv">3</span>),<span class="st">'  var_e = '</span>,<span class="fu">round</span>(var_e,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "dU = 0.509  var_e = 0.0202"</code></pre>
</div>
</div>
<p>The observed score standardized mean difference is substantially lower than the true score SMD (.286 vs .509). In order to correct the observed score correlation for attenuation, we can calculate it by hand. Lets correct the observed standardized mean difference for measurement error variance using the equations in <a href="#sec-d-SMD"><span>Section&nbsp;5.6.2</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the pooled reliability</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>ryy_P <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(((nA<span class="dv">-1</span>)<span class="sc">*</span>ryyA<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (nB<span class="dv">-1</span>)<span class="sc">*</span>ryyB<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (nA<span class="sc">+</span>nB<span class="dv">-2</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># correct correlation coefficient</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>dc <span class="ot">&lt;-</span> dy <span class="sc">/</span> <span class="fu">sqrt</span>(ryy_P)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># correct sampling variance</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>var_e_c <span class="ot">&lt;-</span> var_e_o <span class="sc">/</span> <span class="fu">sqrt</span>(ryyA)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">'rc = '</span>,<span class="fu">round</span>(dc,<span class="dv">3</span>),<span class="st">'  var_e_c = '</span>,<span class="fu">round</span>(var_e_c,<span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "rc = 0.32  var_e_c = 0.0233"</code></pre>
</div>
</div>
<p>Now lets correct the correlation with the <code>correct_r()</code> function. The <code>correct_d()</code> function only takes in the total sample reliability, therefore we can extract the total sample reliability from the simulated dataset and then use the resulting reliability coefficient in the <code>ryy</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># total sample reliability</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>ryy <span class="ot">=</span> data<span class="sc">$</span>overall_results<span class="sc">$</span>observed<span class="sc">$</span>parallel_ryyi_total[<span class="dv">1</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># correct correlation</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">correct_d</span>(<span class="at">d =</span> dy,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">ryy =</span> ryy,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">n1 =</span> n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>d Values Corrected for Measurement Error:
---------------------------------------------------------------------------------------
  value CI_LL_95 CI_UL_95   n n_effective
1 0.322 -0.00878    0.667 200         142</code></pre>
</div>
</div>
<p>As we can see, the corrected correlation (<span class="math inline">\(d_c = .32\)</span>) is a more accurate estimate of the true score population SMD <span class="math inline">\(\delta_U = .500\)</span>, than the observed score correlation (<span class="math inline">\(r_{xy}=.273\)</span>).</p>
</section>
</section>
<section id="sec-lim-information" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-lim-information"><span class="header-section-number">5.7</span> Estimating Reliability with Limited Information</h2>
<p>Reliability estimates should preferably be calculated from within the study’s sample, however there are a couple of ways to estimate reliability when this information is not provided. A common way to obtain an estimate of the reliability is to look in meta-analyses or a test manuals. If the number of items in a study differs from the test manual, you can approximate the reliability of the study’s test, with a re-arrangement of the Spearman-Brown prophecy formula,</p>
<p><span class="math display">\[
r_{xx'_{study}} \approx \frac{1}{\frac{\kappa_{\text{ref}}}{\kappa_{\text{study}}} \left(\frac{1}{r_{xx'_{study}}} - 1\right) + 1}.
\]</span></p>
<p>Where <span class="math inline">\(\kappa_{\text{ref}}\)</span> and <span class="math inline">\(\kappa_{\text{study}}\)</span> denote the number of items in the reference test and the test used in the study, respectively.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-borsboom2002" class="csl-entry" role="listitem">
Borsboom, Denny, and Gideon J Mellenbergh. 2002. <span>“True Scores, Latent Variables, and Constructs: A Comment on Schmidt and Hunter.”</span>
</div>
<div id="ref-borsboom2004" class="csl-entry" role="listitem">
Borsboom, Denny, Gideon J. Mellenbergh, and Jaap Van Heerden. 2004. <span>“The Concept of Validity.”</span> <em>Psychological Review</em> 111 (4): 1061–71. <a href="https://doi.org/10.1037/0033-295X.111.4.1061">https://doi.org/10.1037/0033-295X.111.4.1061</a>.
</div>
<div id="ref-cronbach1955" class="csl-entry" role="listitem">
Cronbach, Lee J., and Paul E. Meehl. 1955. <span>“Construct Validity in Psychological Tests.”</span> <em>Psychological Bulletin</em> 52 (4): 281–302. <a href="https://doi.org/10.1037/h0040957">https://doi.org/10.1037/h0040957</a>.
</div>
<div id="ref-galton1907" class="csl-entry" role="listitem">
Galton, Francis. 1907. <span>“Vox Populi.”</span> <em>Nature</em> 75 (1949): 450–51. <a href="https://doi.org/10.1038/075450a0">https://doi.org/10.1038/075450a0</a>.
</div>
<div id="ref-haertel2006" class="csl-entry" role="listitem">
Haertel, Edward H. 2006. <span>“3. Reliability.”</span> In, 4th ed.
</div>
<div id="ref-hunter1990a" class="csl-entry" role="listitem">
Hunter, John E., and Frank L. Schmidt. 1990. <em>Methods of meta-analysis: correcting error and bias in research findings</em>. Newbury Park: Sage Publications.
</div>
<div id="ref-kelley1927" class="csl-entry" role="listitem">
Kelley, Truman Lee. 1927. <em>Interpretation of Educational Measurements</em>. World Book Company.
</div>
<div id="ref-mendoza1987" class="csl-entry" role="listitem">
Mendoza, Jorge L., and Michael Mumford. 1987. <span>“Corrections for Attenuation and Range Restriction on the Predictor.”</span> <em>Journal of Educational Statistics</em> 12 (3): 282–93. <a href="https://doi.org/10.3102/10769986012003282">https://doi.org/10.3102/10769986012003282</a>.
</div>
<div id="ref-psych:p2017" class="csl-entry" role="listitem">
<span>“Psych: Procedures for Personality and Psychological Research.”</span> 2017. <a href="https://CRAN.R-project.org/package=psych">https://CRAN.R-project.org/package=psych</a>.
</div>
<div id="ref-spearman1904" class="csl-entry" role="listitem">
Spearman, C. 1904. <span>“The Proof and Measurement of Association Between Two Things.”</span> <em>International Journal of Epidemiology</em> 39 (5): 1137–50. <a href="https://doi.org/10.1093/ije/dyq191">https://doi.org/10.1093/ije/dyq191</a>.
</div>
<div id="ref-viswesvaran2014" class="csl-entry" role="listitem">
Viswesvaran, Chockalingam, Deniz S. Ones, Frank L. Schmidt, Huy Le, and In-Sue Oh. 2014. <span>“Measurement Error Obfuscates Scientific Knowledge: Path to Cumulative Knowledge Requires Corrections for Unreliability and Psychometric Meta-Analyses.”</span> <em>Industrial and Organizational Psychology</em> 7 (4): 507–18. <a href="https://doi.org/10.1017/S1754942600006799">https://doi.org/10.1017/S1754942600006799</a>.
</div>
<div id="ref-wiernik2020" class="csl-entry" role="listitem">
Wiernik, Brenton M., and Jeffrey A. Dahlke. 2020. <span>“Obtaining Unbiased Results in Meta-Analysis: The Importance of Correcting for Statistical Artifacts.”</span> <em>Advances in Methods and Practices in Psychological Science</em> 3 (1): 94–123. <a href="https://doi.org/10.1177/2515245919885611">https://doi.org/10.1177/2515245919885611</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./small_samples.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Small Samples</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./misclassification.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Group Misclassification</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>